module.exports = {
  // ── People ──────────────────────────────────────────────────────────────────
  employees: [
    { name: "Alice Johnson",    dept: "Engineering", role: "Senior Dev",         level: "Senior",     status: "active",   hire_date: "2021-03-15", salary: 145000, manager: "Iris Patel",    location: "NYC",    performance: 4.5 },
    { name: "Bob Smith",        dept: "Marketing",   role: "Marketing Manager",  level: "Manager",    status: "active",   hire_date: "2019-07-01", salary: 118000, manager: "Sandra Kim",    location: "LA",     performance: 3.8 },
    { name: "Carol White",      dept: "Design",      role: "UX Lead",            level: "Senior",     status: "on-leave", hire_date: "2020-11-22", salary: 132000, manager: "Sandra Kim",    location: "NYC",    performance: 4.2 },
    { name: "David Brown",      dept: "Engineering", role: "Junior Dev",         level: "Junior",     status: "active",   hire_date: "2023-01-10", salary: 92000,  manager: "Alice Johnson", location: "Remote", performance: 3.5 },
    { name: "Eve Davis",        dept: "Sales",       role: "Account Executive",  level: "Senior",     status: "active",   hire_date: "2022-05-18", salary: 98000,  manager: "Marcus Reid",   location: "Chicago",performance: 4.7 },
    { name: "Frank Miller",     dept: "Engineering", role: "DevOps Engineer",    level: "Senior",     status: "active",   hire_date: "2020-09-03", salary: 138000, manager: "Iris Patel",    location: "NYC",    performance: 4.1 },
    { name: "Grace Lee",        dept: "HR",          role: "HR Manager",         level: "Manager",    status: "active",   hire_date: "2018-04-12", salary: 112000, manager: "Sandra Kim",    location: "NYC",    performance: 4.0 },
    { name: "Henry Chen",       dept: "Finance",     role: "Financial Analyst",  level: "Mid",        status: "active",   hire_date: "2021-08-30", salary: 105000, manager: "Sandra Kim",    location: "Remote", performance: 3.9 },
    { name: "Iris Patel",       dept: "Engineering", role: "VP Engineering",     level: "Leadership", status: "active",   hire_date: "2019-02-14", salary: 198000, manager: "Sandra Kim",    location: "NYC",    performance: 4.8 },
    { name: "Jake Torres",      dept: "Sales",       role: "Sales Rep",          level: "Junior",     status: "active",   hire_date: "2023-06-05", salary: 85000,  manager: "Marcus Reid",   location: "Chicago",performance: 3.6 },
    { name: "Karen Nguyen",     dept: "Engineering", role: "Backend Dev",        level: "Mid",        status: "active",   hire_date: "2022-02-28", salary: 128000, manager: "Alice Johnson", location: "NYC",    performance: 4.3 },
    { name: "Liam Foster",      dept: "Marketing",   role: "Content Strategist", level: "Mid",        status: "active",   hire_date: "2021-11-15", salary: 94000,  manager: "Bob Smith",     location: "LA",     performance: 3.7 },
    { name: "Maya Rodriguez",   dept: "Design",      role: "Product Designer",   level: "Mid",        status: "active",   hire_date: "2022-07-20", salary: 108000, manager: "Carol White",   location: "Remote", performance: 4.4 },
    { name: "Nathan Wu",        dept: "Engineering", role: "ML Engineer",        level: "Senior",     status: "active",   hire_date: "2020-05-11", salary: 162000, manager: "Iris Patel",    location: "NYC",    performance: 4.6 },
    { name: "Olivia Hart",      dept: "Sales",       role: "Sales Manager",      level: "Manager",    status: "active",   hire_date: "2018-09-30", salary: 135000, manager: "Marcus Reid",   location: "Chicago",performance: 4.2 },
    { name: "Paul Kim",         dept: "Engineering", role: "Frontend Dev",       level: "Mid",        status: "on-leave", hire_date: "2021-06-14", salary: 118000, manager: "Alice Johnson", location: "Remote", performance: 3.8 },
    { name: "Quinn Patel",      dept: "Finance",     role: "Controller",         level: "Senior",     status: "active",   hire_date: "2017-03-22", salary: 148000, manager: "Sandra Kim",    location: "NYC",    performance: 4.5 },
    { name: "Rachel Thompson",  dept: "HR",          role: "Recruiter",          level: "Mid",        status: "active",   hire_date: "2022-10-05", salary: 88000,  manager: "Grace Lee",     location: "NYC",    performance: 3.9 },
    { name: "Sam Ortiz",        dept: "Engineering", role: "Security Engineer",  level: "Senior",     status: "active",   hire_date: "2020-01-08", salary: 152000, manager: "Frank Miller",  location: "NYC",    performance: 4.3 },
    { name: "Tina Brooks",      dept: "Marketing",   role: "SEO Specialist",     level: "Junior",     status: "active",   hire_date: "2023-08-21", salary: 78000,  manager: "Bob Smith",     location: "LA",     performance: 3.4 },
    { name: "Uma Singh",        dept: "Design",      role: "Motion Designer",    level: "Junior",     status: "active",   hire_date: "2023-03-14", salary: 82000,  manager: "Carol White",   location: "Remote", performance: 3.6 },
    { name: "Victor Lane",      dept: "Engineering", role: "Data Engineer",      level: "Senior",     status: "active",   hire_date: "2019-11-01", salary: 155000, manager: "Nathan Wu",     location: "NYC",    performance: 4.4 },
    { name: "Wendy Cross",      dept: "Sales",       role: "Account Executive",  level: "Senior",     status: "active",   hire_date: "2020-08-17", salary: 102000, manager: "Olivia Hart",   location: "Chicago",performance: 4.1 },
    { name: "Xander Bell",      dept: "Engineering", role: "Platform Engineer",  level: "Mid",        status: "active",   hire_date: "2022-04-25", salary: 132000, manager: "Frank Miller",  location: "NYC",    performance: 3.9 },
    { name: "Yara Moss",        dept: "Finance",     role: "FP&A Manager",       level: "Manager",    status: "active",   hire_date: "2018-07-09", salary: 142000, manager: "Quinn Patel",   location: "NYC",    performance: 4.6 },
    { name: "Zoe Carson",       dept: "Marketing",   role: "Growth Manager",     level: "Manager",    status: "active",   hire_date: "2019-12-03", salary: 125000, manager: "Bob Smith",     location: "LA",     performance: 4.3 },
    { name: "Marcus Reid",      dept: "Sales",       role: "VP Sales",           level: "Leadership", status: "active",   hire_date: "2016-06-20", salary: 210000, manager: "Sandra Kim",    location: "Chicago",performance: 4.7 },
    { name: "Sandra Kim",       dept: "Executive",   role: "CEO",                level: "C-Suite",    status: "active",   hire_date: "2015-01-01", salary: 320000, manager: null,            location: "NYC",    performance: 4.9 },
  ],

  // ── Projects ─────────────────────────────────────────────────────────────────
  projects: [
    { name: "Website Redesign",      owner: "Carol White",   team: ["Carol White","Maya Rodriguez","Liam Foster"],                        status: "in-progress", pct_complete: 65,  budget: 80000,  spent: 52000,  due_date: "2026-04-15", priority: "high",     dept: "Design" },
    { name: "API Migration v3",      owner: "Alice Johnson", team: ["Alice Johnson","Karen Nguyen","David Brown","Xander Bell"],          status: "in-progress", pct_complete: 40,  budget: 120000, spent: 48000,  due_date: "2026-05-01", priority: "critical", dept: "Engineering" },
    { name: "Mobile App v2",         owner: "David Brown",   team: ["David Brown","Paul Kim","Uma Singh","Maya Rodriguez"],               status: "planning",    pct_complete: 10,  budget: 200000, spent: 20000,  due_date: "2026-06-30", priority: "high",     dept: "Engineering" },
    { name: "Analytics Dashboard",   owner: "Bob Smith",     team: ["Bob Smith","Henry Chen","Nathan Wu"],                               status: "completed",   pct_complete: 100, budget: 45000,  spent: 43200,  due_date: "2026-03-01", priority: "medium",   dept: "Marketing" },
    { name: "Security Audit Q1",     owner: "Iris Patel",    team: ["Sam Ortiz","Frank Miller","Iris Patel"],                            status: "in-progress", pct_complete: 75,  budget: 30000,  spent: 22500,  due_date: "2026-03-25", priority: "critical", dept: "Engineering" },
    { name: "Customer Portal",       owner: "Eve Davis",     team: ["Eve Davis","Karen Nguyen","Maya Rodriguez","Tina Brooks"],          status: "planning",    pct_complete: 5,   budget: 95000,  spent: 4750,   due_date: "2026-07-01", priority: "high",     dept: "Sales" },
    { name: "Data Warehouse Phase 2",owner: "Henry Chen",    team: ["Victor Lane","Nathan Wu","Henry Chen","Yara Moss"],                 status: "in-progress", pct_complete: 55,  budget: 160000, spent: 88000,  due_date: "2026-05-20", priority: "high",     dept: "Engineering" },
    { name: "ML Recommendation Engine",owner: "Nathan Wu",  team: ["Nathan Wu","Victor Lane","Karen Nguyen"],                           status: "in-progress", pct_complete: 30,  budget: 250000, spent: 75000,  due_date: "2026-08-15", priority: "high",     dept: "Engineering" },
    { name: "Brand Refresh",         owner: "Liam Foster",  team: ["Liam Foster","Carol White","Uma Singh","Tina Brooks"],              status: "in-progress", pct_complete: 50,  budget: 55000,  spent: 27500,  due_date: "2026-04-30", priority: "medium",   dept: "Marketing" },
    { name: "Sales CRM Upgrade",     owner: "Olivia Hart",  team: ["Olivia Hart","Eve Davis","Jake Torres","Wendy Cross"],              status: "planning",    pct_complete: 15,  budget: 70000,  spent: 10500,  due_date: "2026-06-01", priority: "high",     dept: "Sales" },
    { name: "DevOps CI/CD Overhaul", owner: "Frank Miller", team: ["Frank Miller","Sam Ortiz","Xander Bell"],                          status: "in-progress", pct_complete: 80,  budget: 40000,  spent: 32000,  due_date: "2026-03-31", priority: "high",     dept: "Engineering" },
    { name: "GDPR Compliance Audit", owner: "Grace Lee",    team: ["Grace Lee","Quinn Patel","Sam Ortiz","Rachel Thompson"],            status: "completed",   pct_complete: 100, budget: 25000,  spent: 24100,  due_date: "2026-02-28", priority: "critical", dept: "HR" },
    { name: "Investor Deck Q2",      owner: "Yara Moss",    team: ["Yara Moss","Henry Chen","Sandra Kim"],                             status: "planning",    pct_complete: 20,  budget: 15000,  spent: 3000,   due_date: "2026-04-05", priority: "medium",   dept: "Finance" },
    { name: "SSO Identity Platform", owner: "Sam Ortiz",    team: ["Sam Ortiz","Frank Miller","Alice Johnson"],                        status: "in-progress", pct_complete: 60,  budget: 85000,  spent: 51000,  due_date: "2026-05-15", priority: "critical", dept: "Engineering" },
  ],

  // ── KPIs & Metrics ───────────────────────────────────────────────────────────
  kpi_metrics: [
    { label: "Monthly Revenue",      value: "$2.84M",   current_val: 2840000,  target: 2700000, delta: "+5.2%",   trend: "up",   category: "revenue" },
    { label: "ARR",                  value: "$34.1M",   current_val: 34100000, target: 36000000,delta: "-5.3%",   trend: "down", category: "revenue" },
    { label: "Active Users",         value: "142,300",  current_val: 142300,   target: 150000,  delta: "+8.1%",   trend: "up",   category: "product" },
    { label: "DAU / MAU",            value: "38%",      current_val: 38,       target: 42,      delta: "-4pts",   trend: "down", category: "product" },
    { label: "Support Tickets Open", value: "47",       current_val: 47,       target: 40,      delta: "+17.5%",  trend: "down", category: "support" },
    { label: "Avg Resolution Time",  value: "4.2h",     current_val: 4.2,      target: 3.0,     delta: "+40%",    trend: "down", category: "support" },
    { label: "Uptime SLA",           value: "99.97%",   current_val: 99.97,    target: 99.9,    delta: "+0.07pts",trend: "up",   category: "infra" },
    { label: "Avg API Latency",      value: "142ms",    current_val: 142,      target: 200,     delta: "-29%",    trend: "up",   category: "infra" },
    { label: "NPS Score",            value: "72",       current_val: 72,       target: 70,      delta: "+2.9%",   trend: "up",   category: "product" },
    { label: "MoM Conversion Rate",  value: "3.8%",     current_val: 3.8,      target: 4.0,     delta: "-0.2pts", trend: "down", category: "revenue" },
    { label: "Gross Margin",         value: "68.4%",    current_val: 68.4,     target: 70,      delta: "-1.6pts", trend: "down", category: "revenue" },
    { label: "CAC",                  value: "$312",     current_val: 312,      target: 280,     delta: "+11.4%",  trend: "down", category: "revenue" },
    { label: "LTV",                  value: "$4,820",   current_val: 4820,     target: 5000,    delta: "-3.6%",   trend: "down", category: "revenue" },
    { label: "LTV:CAC Ratio",        value: "15.4x",    current_val: 15.4,     target: 17.8,    delta: "-13.5%",  trend: "down", category: "revenue" },
    { label: "Net Dollar Retention", value: "108%",     current_val: 108,      target: 110,     delta: "-2pts",   trend: "down", category: "revenue" },
    { label: "Churn Rate",           value: "1.2%",     current_val: 1.2,      target: 1.0,     delta: "+0.2pts", trend: "down", category: "revenue" },
    { label: "Employees (FTE)",      value: "127",      current_val: 127,      target: 140,     delta: "-9.3%",   trend: "neutral",category:"people" },
    { label: "Offer Acceptance Rate",value: "74%",      current_val: 74,       target: 85,      delta: "-11pts",  trend: "down", category: "people" },
    { label: "Voluntary Attrition",  value: "8.4%",     current_val: 8.4,      target: 7.0,     delta: "+1.4pts", trend: "down", category: "people" },
  ],

  // ── Revenue & Finance ────────────────────────────────────────────────────────
  monthly_revenue: [
    { month: "Apr 2025", mrr: 2210000, new_arr: 185000, expansion: 62000, churn: 28000, net_new: 219000 },
    { month: "May 2025", mrr: 2290000, new_arr: 198000, expansion: 71000, churn: 31000, net_new: 238000 },
    { month: "Jun 2025", mrr: 2380000, new_arr: 220000, expansion: 68000, churn: 35000, net_new: 253000 },
    { month: "Jul 2025", mrr: 2440000, new_arr: 195000, expansion: 55000, churn: 38000, net_new: 212000 },
    { month: "Aug 2025", mrr: 2510000, new_arr: 241000, expansion: 72000, churn: 29000, net_new: 284000 },
    { month: "Sep 2025", mrr: 2590000, new_arr: 268000, expansion: 84000, churn: 33000, net_new: 319000 },
    { month: "Oct 2025", mrr: 2640000, new_arr: 215000, expansion: 61000, churn: 41000, net_new: 235000 },
    { month: "Nov 2025", mrr: 2690000, new_arr: 228000, expansion: 78000, churn: 36000, net_new: 270000 },
    { month: "Dec 2025", mrr: 2750000, new_arr: 310000, expansion: 92000, churn: 44000, net_new: 358000 },
    { month: "Jan 2026", mrr: 2780000, new_arr: 195000, expansion: 58000, churn: 52000, net_new: 201000 },
    { month: "Feb 2026", mrr: 2810000, new_arr: 212000, expansion: 65000, churn: 39000, net_new: 238000 },
    { month: "Mar 2026", mrr: 2840000, new_arr: 224000, expansion: 69000, churn: 42000, net_new: 251000 },
  ],

  revenue_by_segment: [
    { segment: "Enterprise",    mrr: 1420000, customers: 38,  avg_acv: 448421, churn_rate: 0.4, ndr: 118 },
    { segment: "Mid-Market",    mrr: 854000,  customers: 142, avg_acv: 72197,  churn_rate: 1.1, ndr: 108 },
    { segment: "SMB",           mrr: 412000,  customers: 891, avg_acv: 5546,   churn_rate: 2.8, ndr: 94  },
    { segment: "Startup",       mrr: 154000,  customers: 1240,avg_acv: 1490,   churn_rate: 4.2, ndr: 88  },
  ],

  // ── Budget ────────────────────────────────────────────────────────────────────
  budget: [
    { department: "Engineering",  allocated: 5200000, spent: 3870000, headcount: 12, q1_forecast: 1420000 },
    { department: "Marketing",    allocated: 1800000, spent: 1620000, headcount: 5,  q1_forecast: 495000  },
    { department: "Sales",        allocated: 2400000, spent: 1980000, headcount: 6,  q1_forecast: 680000  },
    { department: "Design",       allocated: 950000,  spent: 610000,  headcount: 4,  q1_forecast: 248000  },
    { department: "HR",           allocated: 750000,  spent: 480000,  headcount: 3,  q1_forecast: 195000  },
    { department: "Finance",      allocated: 600000,  spent: 410000,  headcount: 3,  q1_forecast: 162000  },
    { department: "DevOps/Infra", allocated: 1400000, spent: 1280000, headcount: 3,  q1_forecast: 368000  },
    { department: "Executive",    allocated: 800000,  spent: 580000,  headcount: 1,  q1_forecast: 210000  },
  ],

  // ── Sales Pipeline ────────────────────────────────────────────────────────────
  sales_pipeline: [
    { deal: "Acme Corp ERP Suite",       stage: "Proposal",    value: 185000,  probability: 60, close_date: "2026-04-10", rep: "Eve Davis",   industry: "Manufacturing", source: "Outbound" },
    { deal: "Globex SaaS Expansion",     stage: "Negotiation", value: 342000,  probability: 80, close_date: "2026-03-28", rep: "Jake Torres", industry: "Tech",          source: "Expansion" },
    { deal: "Initech Platform",          stage: "Discovery",   value: 92000,   probability: 30, close_date: "2026-05-15", rep: "Eve Davis",   industry: "Finance",       source: "Inbound" },
    { deal: "Umbrella Corp Renewal",     stage: "Closed Won",  value: 510000,  probability: 100,close_date: "2026-03-01", rep: "Jake Torres", industry: "Healthcare",    source: "Renewal" },
    { deal: "Soylent Analytics Pro",     stage: "Proposal",    value: 167500,  probability: 55, close_date: "2026-04-22", rep: "Wendy Cross", industry: "Food & Bev",    source: "Inbound" },
    { deal: "Cyberdyne Platform",        stage: "Discovery",   value: 495000,  probability: 25, close_date: "2026-06-30", rep: "Eve Davis",   industry: "Defense",       source: "Outbound" },
    { deal: "Stark Industries MDM",      stage: "Negotiation", value: 288000,  probability: 75, close_date: "2026-03-31", rep: "Wendy Cross", industry: "Tech",          source: "Outbound" },
    { deal: "Wayne Enterprises SIEM",    stage: "Proposal",    value: 425000,  probability: 50, close_date: "2026-05-01", rep: "Olivia Hart", industry: "Finance",       source: "Partner" },
    { deal: "Oscorp Data Ops",           stage: "Closed Won",  value: 128000,  probability: 100,close_date: "2026-02-20", rep: "Jake Torres", industry: "Biotech",       source: "Inbound" },
    { deal: "LexCorp Cloud Migration",   stage: "Discovery",   value: 210000,  probability: 20, close_date: "2026-07-15", rep: "Olivia Hart", industry: "Energy",        source: "Outbound" },
    { deal: "Pied Piper API Gateway",    stage: "Negotiation", value: 95000,   probability: 70, close_date: "2026-04-05", rep: "Wendy Cross", industry: "Tech",          source: "Inbound" },
    { deal: "Hooli Enterprise SSO",      stage: "Closed Lost", value: 380000,  probability: 0,  close_date: "2026-02-15", rep: "Eve Davis",   industry: "Tech",          source: "Outbound" },
    { deal: "Dunder Mifflin SaaS",       stage: "Proposal",    value: 45000,   probability: 65, close_date: "2026-04-18", rep: "Jake Torres", industry: "Retail",        source: "Inbound" },
    { deal: "Vehement Capital Analytics",stage: "Closed Won",  value: 840000,  probability: 100,close_date: "2026-03-10", rep: "Olivia Hart", industry: "Finance",       source: "Outbound" },
  ],

  // ── Support Tickets ───────────────────────────────────────────────────────────
  support: [
    { id: "TKT-1052", subject: "OAuth2 tokens expiring prematurely",            priority: "critical", status: "open",        assignee: "Sam Ortiz",     category: "Auth",       hours_open: 2,  created: "2026-03-17" },
    { id: "TKT-1051", subject: "Login SSO broken after v3.2 deploy",            priority: "critical", status: "in-progress", assignee: "Frank Miller",  category: "Auth",       hours_open: 5,  created: "2026-03-17" },
    { id: "TKT-1049", subject: "Dashboard export returns empty CSV",            priority: "high",     status: "in-progress", assignee: "Alice Johnson", category: "Reports",    hours_open: 18, created: "2026-03-16" },
    { id: "TKT-1048", subject: "Slow query on /api/reports endpoint (>8s)",     priority: "high",     status: "in-progress", assignee: "Karen Nguyen",  category: "Performance",hours_open: 26, created: "2026-03-15" },
    { id: "TKT-1047", subject: "Webhook retry loop causing duplicate charges",  priority: "critical", status: "open",        assignee: "Frank Miller",  category: "Billing",    hours_open: 8,  created: "2026-03-16" },
    { id: "TKT-1045", subject: "Email notifications not sending (SMTP)",        priority: "high",     status: "open",        assignee: "Frank Miller",  category: "Comms",      hours_open: 42, created: "2026-03-14" },
    { id: "TKT-1043", subject: "File upload silently fails >50MB",              priority: "medium",   status: "in-progress", assignee: "David Brown",   category: "Upload",     hours_open: 31, created: "2026-03-15" },
    { id: "TKT-1041", subject: "UI rendering glitch on mobile Safari iOS 17",   priority: "medium",   status: "open",        assignee: "Paul Kim",      category: "Frontend",   hours_open: 71, created: "2026-03-12" },
    { id: "TKT-1040", subject: "User can't update billing address (400 error)", priority: "medium",   status: "resolved",    assignee: "Alice Johnson", category: "Billing",    hours_open: 8,  created: "2026-03-16" },
    { id: "TKT-1038", subject: "Password reset link expires in 5min not 1hr",   priority: "low",      status: "resolved",    assignee: "Grace Lee",     category: "Auth",       hours_open: 55, created: "2026-03-13" },
    { id: "TKT-1037", subject: "CSV import drops unicode characters",           priority: "medium",   status: "open",        assignee: "Karen Nguyen",  category: "Data",       hours_open: 88, created: "2026-03-11" },
    { id: "TKT-1035", subject: "MFA enrollment page blank on Firefox",          priority: "high",     status: "open",        assignee: "Paul Kim",      category: "Auth",       hours_open: 96, created: "2026-03-10" },
    { id: "TKT-1033", subject: "Scheduled report email attached wrong file",    priority: "medium",   status: "in-progress", assignee: "David Brown",   category: "Reports",    hours_open: 112,created: "2026-03-09" },
    { id: "TKT-1030", subject: "API rate limit headers missing from response",  priority: "low",      status: "resolved",    assignee: "Xander Bell",   category: "API",        hours_open: 24, created: "2026-03-15" },
    { id: "TKT-1028", subject: "Tooltip overlaps chart legend at small viewports",priority: "low",    status: "open",        assignee: "Paul Kim",      category: "Frontend",   hours_open: 140,created: "2026-03-07" },
  ],

  // ── Inventory ─────────────────────────────────────────────────────────────────
  inventory: [
    { item: "MacBook Pro 16\" M3",    sku: "HW-011", qty: 8,  capacity: 20, unit: "units", status: "in-stock",     reorder_point: 5,  unit_cost: 3499, supplier: "Apple",    lead_days: 14 },
    { item: "Dell XPS 15",            sku: "HW-001", qty: 12, capacity: 20, unit: "units", status: "in-stock",     reorder_point: 5,  unit_cost: 1899, supplier: "Dell",     lead_days: 7  },
    { item: "USB-C Hub 7-port",       sku: "HW-002", qty: 3,  capacity: 30, unit: "units", status: "low-stock",    reorder_point: 10, unit_cost: 79,   supplier: "Anker",    lead_days: 3  },
    { item: "Standing Desk Uplift",   sku: "FN-001", qty: 0,  capacity: 10, unit: "units", status: "out-of-stock",  reorder_point: 3,  unit_cost: 1299, supplier: "Uplift",   lead_days: 21 },
    { item: "Monitor 32\" 4K LG",    sku: "HW-003", qty: 8,  capacity: 15, unit: "units", status: "in-stock",     reorder_point: 4,  unit_cost: 899,  supplier: "LG",       lead_days: 10 },
    { item: "Mechanical Keyboard",    sku: "HW-004", qty: 2,  capacity: 25, unit: "units", status: "low-stock",    reorder_point: 8,  unit_cost: 149,  supplier: "Keychron", lead_days: 5  },
    { item: "Webcam Logitech 4K",     sku: "HW-005", qty: 15, capacity: 20, unit: "units", status: "in-stock",     reorder_point: 5,  unit_cost: 199,  supplier: "Logitech", lead_days: 4  },
    { item: "Ergonomic Chair Steelcase",sku:"FN-002", qty: 1, capacity: 12, unit: "units", status: "low-stock",    reorder_point: 4,  unit_cost: 1650, supplier: "Steelcase",lead_days: 28 },
    { item: "Sony WH-1000XM5",        sku: "HW-006", qty: 0,  capacity: 15, unit: "units", status: "out-of-stock",  reorder_point: 5,  unit_cost: 349,  supplier: "Sony",     lead_days: 7  },
    { item: "iPad Pro 12.9\" M4",     sku: "HW-012", qty: 5,  capacity: 10, unit: "units", status: "in-stock",     reorder_point: 3,  unit_cost: 1099, supplier: "Apple",    lead_days: 14 },
    { item: "Thunderbolt Dock",       sku: "HW-013", qty: 18, capacity: 25, unit: "units", status: "in-stock",     reorder_point: 6,  unit_cost: 249,  supplier: "CalDigit", lead_days: 5  },
    { item: "Office Chair Mesh Mid",  sku: "FN-003", qty: 6,  capacity: 20, unit: "units", status: "in-stock",     reorder_point: 5,  unit_cost: 425,  supplier: "HON",      lead_days: 14 },
    { item: "NAS Synology 4-bay",     sku: "HW-014", qty: 2,  capacity: 5,  unit: "units", status: "low-stock",    reorder_point: 2,  unit_cost: 699,  supplier: "Synology", lead_days: 10 },
  ],

  // ── Sprint / Engineering Velocity ────────────────────────────────────────────
  sprint: [
    { story: "OAuth2 token refresh endpoint",       points: 8,  status: "done",        assignee: "Alice Johnson", sprint: "Sprint 22", epic: "Auth" },
    { story: "Export pipeline to PDF/CSV",          points: 5,  status: "done",        assignee: "David Brown",   sprint: "Sprint 22", epic: "Reports" },
    { story: "Dark/light mode theme toggle",        points: 3,  status: "done",        assignee: "Paul Kim",      sprint: "Sprint 22", epic: "UI" },
    { story: "Bulk user import via CSV",            points: 13, status: "in-progress", assignee: "Karen Nguyen",  sprint: "Sprint 22", epic: "Admin" },
    { story: "Webhook retry with exponential backoff",points:8,  status: "in-progress", assignee: "Frank Miller",  sprint: "Sprint 22", epic: "Infra" },
    { story: "Rate limiting middleware (Redis)",    points: 5,  status: "todo",        assignee: "Alice Johnson", sprint: "Sprint 22", epic: "Infra" },
    { story: "Dashboard widget drag-and-drop",      points: 13, status: "todo",        assignee: "Paul Kim",      sprint: "Sprint 22", epic: "UI" },
    { story: "Mobile push notifications (FCM)",     points: 8,  status: "blocked",     assignee: "David Brown",   sprint: "Sprint 22", epic: "Mobile" },
    { story: "SAML SSO enterprise connector",       points: 13, status: "done",        assignee: "Sam Ortiz",     sprint: "Sprint 21", epic: "Auth" },
    { story: "Recharts migration from v1",          points: 8,  status: "done",        assignee: "Paul Kim",      sprint: "Sprint 21", epic: "UI" },
    { story: "Multi-tenant data isolation audit",   points: 13, status: "done",        assignee: "Sam Ortiz",     sprint: "Sprint 21", epic: "Security" },
    { story: "Payment webhook idempotency keys",    points: 8,  status: "done",        assignee: "Karen Nguyen",  sprint: "Sprint 21", epic: "Billing" },
    { story: "Real-time notification service",      points: 13, status: "in-progress", assignee: "Xander Bell",   sprint: "Sprint 21", epic: "Infra" },
    { story: "Admin role permission matrix",        points: 5,  status: "done",        assignee: "Alice Johnson", sprint: "Sprint 21", epic: "Auth" },
  ],

  sprint_velocity: [
    { sprint: "Sprint 17", committed: 52, completed: 45, bugs_closed: 8,  team_size: 6 },
    { sprint: "Sprint 18", committed: 55, completed: 51, bugs_closed: 12, team_size: 6 },
    { sprint: "Sprint 19", committed: 58, completed: 48, bugs_closed: 7,  team_size: 7 },
    { sprint: "Sprint 20", committed: 60, completed: 58, bugs_closed: 14, team_size: 7 },
    { sprint: "Sprint 21", committed: 65, completed: 61, bugs_closed: 10, team_size: 8 },
    { sprint: "Sprint 22", committed: 68, completed: 40, bugs_closed: 6,  team_size: 8 }, // in progress
  ],

  // ── Infrastructure / SRE ─────────────────────────────────────────────────────
  infra_services: [
    { service: "API Gateway",        region: "us-east-1", status: "healthy",  uptime_30d: 99.98, p99_latency_ms: 82,  error_rate_pct: 0.02, cost_month: 4200  },
    { service: "Auth Service",       region: "us-east-1", status: "degraded", uptime_30d: 99.71, p99_latency_ms: 420, error_rate_pct: 0.48, cost_month: 1800  },
    { service: "Data Pipeline",      region: "us-east-1", status: "healthy",  uptime_30d: 99.95, p99_latency_ms: 340, error_rate_pct: 0.05, cost_month: 8900  },
    { service: "Notification Worker",region: "us-east-1", status: "down",     uptime_30d: 98.20, p99_latency_ms: 0,   error_rate_pct: 100,  cost_month: 620   },
    { service: "Report Generator",   region: "us-west-2", status: "healthy",  uptime_30d: 99.91, p99_latency_ms: 1820,error_rate_pct: 0.12, cost_month: 3100  },
    { service: "File Storage CDN",   region: "us-east-1", status: "healthy",  uptime_30d: 100,   p99_latency_ms: 28,  error_rate_pct: 0.00, cost_month: 2400  },
    { service: "Search Index",       region: "us-east-1", status: "healthy",  uptime_30d: 99.88, p99_latency_ms: 95,  error_rate_pct: 0.08, cost_month: 5600  },
    { service: "ML Inference API",   region: "us-west-2", status: "healthy",  uptime_30d: 99.82, p99_latency_ms: 680, error_rate_pct: 0.19, cost_month: 12400 },
    { service: "Billing Processor",  region: "us-east-1", status: "healthy",  uptime_30d: 99.99, p99_latency_ms: 145, error_rate_pct: 0.01, cost_month: 2100  },
    { service: "Analytics DB",       region: "us-east-1", status: "degraded", uptime_30d: 99.60, p99_latency_ms: 8400,error_rate_pct: 0.88, cost_month: 18200 },
  ],

  // ── Marketing / Growth ────────────────────────────────────────────────────────
  marketing_campaigns: [
    { campaign: "Q1 SaaS Summit Sponsorship", channel: "Events",      spend: 45000,  leads: 312, opps: 28, closed: 4, revenue: 185000, roi: 311 },
    { campaign: "LinkedIn ABM Enterprise",    channel: "Paid Social", spend: 28000,  leads: 185, opps: 41, closed: 8, revenue: 420000, roi: 1400},
    { campaign: "Google Search Brand",        channel: "SEM",         spend: 18500,  leads: 892, opps: 67, closed: 14,revenue: 198000, roi: 970 },
    { campaign: "Webinar: AI in Finance",     channel: "Content",     spend: 8200,   leads: 541, opps: 38, closed: 7, revenue: 112000, roi: 1266},
    { campaign: "G2 Review Push",             channel: "Review Sites",spend: 5500,   leads: 228, opps: 19, closed: 5, revenue: 84000,  roi: 1427},
    { campaign: "Cold Outbound SDR",          channel: "Outbound",    spend: 62000,  leads: 1840,opps: 92, closed: 11,revenue: 295000, roi: 376 },
    { campaign: "Partner Referral Program",   channel: "Partners",    spend: 15000,  leads: 148, opps: 52, closed: 18,revenue: 680000, roi: 4433},
    { campaign: "Product Hunt Launch",        channel: "PR/Launch",   spend: 3800,   leads: 2140,opps: 21, closed: 3, revenue: 42000,  roi: 1005},
  ],

  web_analytics: [
    { month: "Oct 2025", sessions: 84200,  pageviews: 312000, signups: 1820, trials: 410, paid_conversions: 62 },
    { month: "Nov 2025", sessions: 91800,  pageviews: 338000, signups: 2140, trials: 488, paid_conversions: 71 },
    { month: "Dec 2025", sessions: 78400,  pageviews: 281000, signups: 1640, trials: 352, paid_conversions: 58 },
    { month: "Jan 2026", sessions: 102100, pageviews: 388000, signups: 2580, trials: 540, paid_conversions: 84 },
    { month: "Feb 2026", sessions: 115400, pageviews: 441000, signups: 2920, trials: 612, paid_conversions: 97 },
    { month: "Mar 2026", sessions: 124800, pageviews: 478000, signups: 3180, trials: 668, paid_conversions: 108},
  ],

  // ── Product Usage ─────────────────────────────────────────────────────────────
  feature_adoption: [
    { feature: "Dashboard Builder",   mau: 98400,  pct_users: 69, satisfaction: 4.4, p99_load_ms: 820  },
    { feature: "Report Scheduler",    mau: 62100,  pct_users: 44, satisfaction: 3.9, p99_load_ms: 1240 },
    { feature: "API Key Management",  mau: 44800,  pct_users: 32, satisfaction: 4.1, p99_load_ms: 310  },
    { feature: "Team Collaboration",  mau: 38200,  pct_users: 27, satisfaction: 3.6, p99_load_ms: 540  },
    { feature: "SSO / SAML",          mau: 29700,  pct_users: 21, satisfaction: 4.6, p99_load_ms: 280  },
    { feature: "Data Connectors",     mau: 25400,  pct_users: 18, satisfaction: 3.8, p99_load_ms: 2100 },
    { feature: "Mobile App",          mau: 18900,  pct_users: 13, satisfaction: 3.2, p99_load_ms: 1580 },
    { feature: "AI Insights (Beta)",  mau: 8200,   pct_users: 6,  satisfaction: 4.2, p99_load_ms: 3400 },
    { feature: "Audit Logs",          mau: 6800,   pct_users: 5,  satisfaction: 4.5, p99_load_ms: 420  },
    { feature: "Webhooks",            mau: 5100,   pct_users: 4,  satisfaction: 3.7, p99_load_ms: 190  },
  ],

  // ── E-Commerce Orders ─────────────────────────────────────────────────────────
  ecommerce_orders: [
    { order_id: "ORD-10481", customer: "Priya Kapoor",    email: "priya.k@gmail.com",     country: "IN", channel: "mobile",  category: "Electronics",    product: "Wireless Earbuds Pro",       sku: "EL-4421", qty: 1, unit_price: 129.99, discount_pct: 10, shipping: 0,    tax: 11.70,  total: 128.69,  status: "delivered",   payment: "UPI",        days_to_ship: 1, return_requested: false, rating: 5 },
    { order_id: "ORD-10480", customer: "James Whitfield", email: "jwhit@hotmail.com",     country: "US", channel: "web",     category: "Apparel",        product: "Merino Wool Sweater (L)",    sku: "AP-1182", qty: 2, unit_price: 89.00,  discount_pct: 0,  shipping: 5.99, tax: 15.30,  total: 199.29,  status: "shipped",     payment: "Visa",       days_to_ship: 2, return_requested: false, rating: null },
    { order_id: "ORD-10479", customer: "Sofia Alvarez",   email: "s.alvarez@outlook.com", country: "MX", channel: "web",     category: "Home & Garden",  product: "Cast Iron Dutch Oven 5.5qt", sku: "HG-0882", qty: 1, unit_price: 74.95,  discount_pct: 15, shipping: 9.99, tax: 9.60,   total: 83.44,   status: "delivered",   payment: "MasterCard", days_to_ship: 3, return_requested: false, rating: 4 },
    { order_id: "ORD-10478", customer: "Luca Moretti",    email: "luca.m@libero.it",      country: "IT", channel: "mobile",  category: "Sports",         product: "Foam Roller Deep Tissue",    sku: "SP-3310", qty: 1, unit_price: 39.99,  discount_pct: 0,  shipping: 4.50, tax: 8.84,   total: 48.33,   status: "processing",  payment: "PayPal",     days_to_ship: null, return_requested: false, rating: null },
    { order_id: "ORD-10477", customer: "Mei Lin",         email: "meilin88@qq.com",       country: "CN", channel: "app",     category: "Beauty",         product: "Vitamin C Serum 30ml",       sku: "BT-0241", qty: 3, unit_price: 24.50,  discount_pct: 20, shipping: 0,    tax: 5.88,   total: 64.68,   status: "delivered",   payment: "Alipay",     days_to_ship: 1, return_requested: false, rating: 5 },
    { order_id: "ORD-10476", customer: "Tom Baxter",      email: "tbaxter@gmail.com",     country: "AU", channel: "web",     category: "Electronics",    product: "USB-C Docking Station",      sku: "EL-3314", qty: 1, unit_price: 199.00, discount_pct: 0,  shipping: 12.00,tax: 19.90,  total: 230.90,  status: "delivered",   payment: "Visa",       days_to_ship: 4, return_requested: true,  rating: 2 },
    { order_id: "ORD-10475", customer: "Amara Diallo",    email: "a.diallo@orange.fr",    country: "FR", channel: "web",     category: "Books",          product: "The Art of Systems Thinking", sku:"BK-1100", qty: 2, unit_price: 18.99,  discount_pct: 5,  shipping: 3.99, tax: 3.61,   total: 40.58,   status: "delivered",   payment: "CB",         days_to_ship: 2, return_requested: false, rating: 5 },
    { order_id: "ORD-10474", customer: "Carlos Mendez",   email: "cmendez@empresa.co",    country: "CO", channel: "mobile",  category: "Toys & Games",   product: "LEGO Technic Bugatti Set",   sku: "TY-5501", qty: 1, unit_price: 449.95, discount_pct: 0,  shipping: 18.00,tax: 46.80,  total: 514.75,  status: "delivered",   payment: "PSE",        days_to_ship: 5, return_requested: false, rating: 5 },
    { order_id: "ORD-10473", customer: "Hannah Schmidt",  email: "h.schmidt@web.de",      country: "DE", channel: "web",     category: "Kitchen",        product: "Nespresso Vertuo Next",      sku: "KT-0771", qty: 1, unit_price: 159.00, discount_pct: 10, shipping: 0,    tax: 27.02,  total: 170.12,  status: "refunded",    payment: "Klarna",     days_to_ship: 2, return_requested: true,  rating: 1 },
    { order_id: "ORD-10472", customer: "Raj Sharma",      email: "rajsharma@gmail.com",   country: "IN", channel: "app",     category: "Fitness",        product: "Smart Jump Rope + App",      sku: "FT-2201", qty: 1, unit_price: 49.99,  discount_pct: 0,  shipping: 2.99, tax: 4.75,   total: 57.73,   status: "delivered",   payment: "UPI",        days_to_ship: 2, return_requested: false, rating: 4 },
    { order_id: "ORD-10471", customer: "Zara Flynn",      email: "zflynn@icloud.com",     country: "IE", channel: "web",     category: "Apparel",        product: "Linen Blazer (S)",           sku: "AP-2290", qty: 1, unit_price: 115.00, discount_pct: 0,  shipping: 6.50, tax: 14.95,  total: 136.45,  status: "shipped",     payment: "Stripe",     days_to_ship: 3, return_requested: false, rating: null },
    { order_id: "ORD-10470", customer: "David Park",      email: "dpark@naver.com",       country: "KR", channel: "app",     category: "Electronics",    product: "Mechanical Keyboard TKL",    sku: "EL-2281", qty: 1, unit_price: 189.00, discount_pct: 5,  shipping: 0,    tax: 18.00,  total: 197.55,  status: "delivered",   payment: "KakaoPay",   days_to_ship: 1, return_requested: false, rating: 5 },
    { order_id: "ORD-10469", customer: "Emma Thompson",   email: "emmathom@gmail.com",    country: "GB", channel: "web",     category: "Pet Supplies",   product: "Orthopedic Dog Bed XL",      sku: "PT-0441", qty: 1, unit_price: 85.00,  discount_pct: 0,  shipping: 9.99, tax: 0,      total: 94.99,   status: "delivered",   payment: "PayPal",     days_to_ship: 4, return_requested: false, rating: 4 },
    { order_id: "ORD-10468", customer: "Ali Hassan",      email: "alihassan@yahoo.com",   country: "AE", channel: "mobile",  category: "Fragrance",      product: "Oud Noir EDP 100ml",         sku: "FR-1188", qty: 2, unit_price: 210.00, discount_pct: 0,  shipping: 0,    tax: 0,      total: 420.00,  status: "delivered",   payment: "CARD",       days_to_ship: 2, return_requested: false, rating: 5 },
    { order_id: "ORD-10467", customer: "Nina Petrov",     email: "nina.p@mail.ru",        country: "RU", channel: "web",     category: "Office",         product: "Ergonomic Lumbar Cushion",   sku: "OF-0321", qty: 1, unit_price: 45.00,  discount_pct: 10, shipping: 7.00, tax: 7.65,   total: 54.15,   status: "cancelled",   payment: "Yandex",     days_to_ship: null, return_requested: false, rating: null },
    { order_id: "ORD-10466", customer: "Marcus Webb",     email: "mwebb@comcast.net",     country: "US", channel: "web",     category: "Tools",          product: "DeWalt 20V Drill Set",       sku: "TL-8801", qty: 1, unit_price: 249.00, discount_pct: 0,  shipping: 0,    tax: 24.90,  total: 273.90,  status: "delivered",   payment: "AmEx",       days_to_ship: 2, return_requested: false, rating: 5 },
    { order_id: "ORD-10465", customer: "Yui Tanaka",      email: "yui.t@docomo.ne.jp",    country: "JP", channel: "app",     category: "Stationery",     product: "Hobonichi Techo Planner",    sku: "ST-0110", qty: 1, unit_price: 32.00,  discount_pct: 0,  shipping: 5.00, tax: 2.88,   total: 39.88,   status: "delivered",   payment: "PayPay",     days_to_ship: 1, return_requested: false, rating: 5 },
    { order_id: "ORD-10464", customer: "Omar Farooq",     email: "ofarooq@gmail.com",     country: "PK", channel: "mobile",  category: "Electronics",    product: "Xiaomi Mi Band 8",           sku: "EL-1129", qty: 2, unit_price: 49.99,  discount_pct: 0,  shipping: 3.00, tax: 9.00,   total: 111.98,  status: "delivered",   payment: "JazzCash",   days_to_ship: 3, return_requested: false, rating: 3 },
    { order_id: "ORD-10463", customer: "Isabelle Dupont", email: "i.dupont@sfr.fr",       country: "FR", channel: "web",     category: "Beauty",         product: "La Roche-Posay Moisturiser", sku: "BT-0488", qty: 2, unit_price: 29.90,  discount_pct: 0,  shipping: 4.90, tax: 12.00,  total: 76.70,   status: "delivered",   payment: "CB",         days_to_ship: 2, return_requested: false, rating: 4 },
    { order_id: "ORD-10462", customer: "Ben Carter",      email: "bencarter@gmail.com",   country: "US", channel: "web",     category: "Outdoor",        product: "Hydro Flask 32oz",           sku: "OD-3341", qty: 3, unit_price: 44.95,  discount_pct: 0,  shipping: 0,    tax: 12.14,  total: 147.00,  status: "delivered",   payment: "Visa",       days_to_ship: 3, return_requested: false, rating: 5 },
  ],

  // ── E-Commerce Products ───────────────────────────────────────────────────────
  ecommerce_products: [
    { sku: "EL-4421", name: "Wireless Earbuds Pro",        category: "Electronics", brand: "SoundCore",   price: 129.99, cost: 38.50, margin_pct: 70.4, inventory: 842,  reorder_at: 200, rating_avg: 4.6, review_count: 3814, return_rate_pct: 2.1, monthly_units: 1240, status: "active",       launched: "2024-09-01" },
    { sku: "EL-3314", name: "USB-C Docking Station",       category: "Electronics", brand: "Anker",       price: 199.00, cost: 72.00, margin_pct: 63.8, inventory: 310,  reorder_at: 80,  rating_avg: 4.1, review_count: 1022, return_rate_pct: 5.8, monthly_units: 380,  status: "active",       launched: "2023-11-15" },
    { sku: "EL-2281", name: "Mechanical Keyboard TKL",     category: "Electronics", brand: "Keychron",    price: 189.00, cost: 54.00, margin_pct: 71.4, inventory: 520,  reorder_at: 100, rating_avg: 4.8, review_count: 5621, return_rate_pct: 1.2, monthly_units: 680,  status: "active",       launched: "2023-06-10" },
    { sku: "EL-1129", name: "Xiaomi Mi Band 8",            category: "Electronics", brand: "Xiaomi",      price: 49.99,  cost: 14.00, margin_pct: 72.0, inventory: 2100, reorder_at: 400, rating_avg: 4.2, review_count: 8940, return_rate_pct: 3.4, monthly_units: 2800, status: "active",       launched: "2024-02-20" },
    { sku: "AP-1182", name: "Merino Wool Sweater",         category: "Apparel",     brand: "Uniqlo",      price: 89.00,  cost: 22.00, margin_pct: 75.3, inventory: 1840, reorder_at: 300, rating_avg: 4.5, review_count: 2210, return_rate_pct: 8.2, monthly_units: 920,  status: "active",       launched: "2024-08-01" },
    { sku: "AP-2290", name: "Linen Blazer",                category: "Apparel",     brand: "COS",         price: 115.00, cost: 31.00, margin_pct: 73.0, inventory: 640,  reorder_at: 120, rating_avg: 4.3, review_count: 814,  return_rate_pct: 11.4,monthly_units: 310,  status: "active",       launched: "2025-03-01" },
    { sku: "HG-0882", name: "Cast Iron Dutch Oven 5.5qt",  category: "Home",        brand: "Lodge",       price: 74.95,  cost: 24.00, margin_pct: 68.0, inventory: 980,  reorder_at: 150, rating_avg: 4.9, review_count: 12800,return_rate_pct: 0.8, monthly_units: 1540, status: "active",       launched: "2021-01-01" },
    { sku: "KT-0771", name: "Nespresso Vertuo Next",       category: "Kitchen",     brand: "Nespresso",   price: 159.00, cost: 58.00, margin_pct: 63.5, inventory: 420,  reorder_at: 80,  rating_avg: 4.4, review_count: 7120, return_rate_pct: 4.1, monthly_units: 580,  status: "active",       launched: "2022-10-01" },
    { sku: "BT-0241", name: "Vitamin C Serum 30ml",        category: "Beauty",      brand: "TruSkin",     price: 24.50,  cost: 4.80,  margin_pct: 80.4, inventory: 3200, reorder_at: 600, rating_avg: 4.5, review_count: 22400,return_rate_pct: 1.9, monthly_units: 4800, status: "active",       launched: "2020-05-01" },
    { sku: "BT-0488", name: "La Roche-Posay Moisturiser",  category: "Beauty",      brand: "La Roche-Posay",price: 29.90,cost: 9.20, margin_pct: 69.2, inventory: 1640, reorder_at: 300, rating_avg: 4.7, review_count: 9800, return_rate_pct: 1.1, monthly_units: 2200, status: "active",       launched: "2019-03-15" },
    { sku: "SP-3310", name: "Foam Roller Deep Tissue",     category: "Sports",      brand: "TriggerPoint",price: 39.99, cost: 10.00, margin_pct: 75.0, inventory: 1820, reorder_at: 250, rating_avg: 4.6, review_count: 6210, return_rate_pct: 2.0, monthly_units: 1100, status: "active",       launched: "2022-01-10" },
    { sku: "FT-2201", name: "Smart Jump Rope + App",       category: "Fitness",     brand: "Tangram",     price: 49.99,  cost: 15.00, margin_pct: 70.0, inventory: 540,  reorder_at: 100, rating_avg: 4.3, review_count: 1840, return_rate_pct: 3.2, monthly_units: 420,  status: "active",       launched: "2024-01-05" },
    { sku: "TL-8801", name: "DeWalt 20V Drill Set",        category: "Tools",       brand: "DeWalt",      price: 249.00, cost: 88.00, margin_pct: 64.7, inventory: 620,  reorder_at: 80,  rating_avg: 4.8, review_count: 4120, return_rate_pct: 1.5, monthly_units: 340,  status: "active",       launched: "2023-03-01" },
    { sku: "TY-5501", name: "LEGO Technic Bugatti Set",    category: "Toys",        brand: "LEGO",        price: 449.95, cost: 148.00,margin_pct: 67.1, inventory: 182,  reorder_at: 40,  rating_avg: 4.9, review_count: 3280, return_rate_pct: 0.6, monthly_units: 210,  status: "active",       launched: "2024-06-01" },
    { sku: "OD-3341", name: "Hydro Flask 32oz",            category: "Outdoor",     brand: "Hydro Flask", price: 44.95,  cost: 11.00, margin_pct: 75.5, inventory: 2840, reorder_at: 400, rating_avg: 4.8, review_count: 18400,return_rate_pct: 0.9, monthly_units: 3200, status: "active",       launched: "2018-07-01" },
    { sku: "FR-1188", name: "Oud Noir EDP 100ml",          category: "Fragrance",   brand: "Maison Oud",  price: 210.00, cost: 42.00, margin_pct: 80.0, inventory: 280,  reorder_at: 50,  rating_avg: 4.7, review_count: 640,  return_rate_pct: 2.8, monthly_units: 180,  status: "active",       launched: "2024-11-01" },
    { sku: "PT-0441", name: "Orthopedic Dog Bed XL",       category: "Pet",         brand: "BarkBox",     price: 85.00,  cost: 28.00, margin_pct: 67.1, inventory: 480,  reorder_at: 80,  rating_avg: 4.5, review_count: 2840, return_rate_pct: 3.9, monthly_units: 520,  status: "active",       launched: "2023-08-15" },
    { sku: "BK-1100", name: "The Art of Systems Thinking", category: "Books",       brand: "Penguin",     price: 18.99,  cost: 3.80,  margin_pct: 80.0, inventory: 4200, reorder_at: 500, rating_avg: 4.6, review_count: 1120, return_rate_pct: 0.5, monthly_units: 880,  status: "active",       launched: "2023-04-01" },
    { sku: "ST-0110", name: "Hobonichi Techo Planner",     category: "Stationery",  brand: "Hobonichi",   price: 32.00,  cost: 10.00, margin_pct: 68.8, inventory: 920,  reorder_at: 150, rating_avg: 4.9, review_count: 4810, return_rate_pct: 0.4, monthly_units: 640,  status: "seasonal",     launched: "2024-10-01" },
    { sku: "OF-0321", name: "Ergonomic Lumbar Cushion",    category: "Office",      brand: "ComfiLife",   price: 45.00,  cost: 12.00, margin_pct: 73.3, inventory: 1240, reorder_at: 200, rating_avg: 4.4, review_count: 9200, return_rate_pct: 3.1, monthly_units: 1020, status: "active",       launched: "2021-06-01" },
  ],

  // ── Clinical Trial Data ───────────────────────────────────────────────────────
  clinical_trial: [
    { patient_id: "PT-001", age: 54, sex: "F", bmi: 28.4, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (200mg)", baseline_hba1c: 8.9, week12_hba1c: 7.1, reduction: 1.8, adverse_events: 0, discontinued: false, comorbidities: ["Hypertension"],            region: "North America" },
    { patient_id: "PT-002", age: 61, sex: "M", bmi: 31.2, condition: "Type 2 Diabetes",  treatment_arm: "Placebo",        baseline_hba1c: 9.1, week12_hba1c: 8.8, reduction: 0.3, adverse_events: 0, discontinued: false, comorbidities: ["Obesity"],                 region: "Europe"        },
    { patient_id: "PT-003", age: 47, sex: "F", bmi: 24.8, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (400mg)", baseline_hba1c: 8.4, week12_hba1c: 6.6, reduction: 1.8, adverse_events: 1, discontinued: false, comorbidities: [],                          region: "Asia-Pacific"  },
    { patient_id: "PT-004", age: 68, sex: "M", bmi: 33.1, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (200mg)", baseline_hba1c: 9.5, week12_hba1c: 7.8, reduction: 1.7, adverse_events: 2, discontinued: false, comorbidities: ["CKD","Hypertension"],      region: "North America" },
    { patient_id: "PT-005", age: 52, sex: "F", bmi: 27.0, condition: "Type 2 Diabetes",  treatment_arm: "Placebo",        baseline_hba1c: 8.7, week12_hba1c: 8.5, reduction: 0.2, adverse_events: 0, discontinued: false, comorbidities: ["Dyslipidaemia"],           region: "Europe"        },
    { patient_id: "PT-006", age: 45, sex: "M", bmi: 26.4, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (400mg)", baseline_hba1c: 8.1, week12_hba1c: 6.2, reduction: 1.9, adverse_events: 0, discontinued: false, comorbidities: [],                          region: "Asia-Pacific"  },
    { patient_id: "PT-007", age: 73, sex: "F", bmi: 29.9, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (200mg)", baseline_hba1c: 9.8, week12_hba1c: 8.1, reduction: 1.7, adverse_events: 3, discontinued: true,  comorbidities: ["Heart Failure","CKD"],     region: "North America" },
    { patient_id: "PT-008", age: 39, sex: "M", bmi: 23.2, condition: "Type 2 Diabetes",  treatment_arm: "Placebo",        baseline_hba1c: 8.0, week12_hba1c: 7.8, reduction: 0.2, adverse_events: 0, discontinued: false, comorbidities: [],                          region: "Latin America" },
    { patient_id: "PT-009", age: 57, sex: "F", bmi: 30.8, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (400mg)", baseline_hba1c: 9.2, week12_hba1c: 7.0, reduction: 2.2, adverse_events: 1, discontinued: false, comorbidities: ["Hypertension"],            region: "Europe"        },
    { patient_id: "PT-010", age: 64, sex: "M", bmi: 35.4, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (200mg)", baseline_hba1c: 10.1,week12_hba1c: 8.3, reduction: 1.8, adverse_events: 1, discontinued: false, comorbidities: ["Obesity","Dyslipidaemia"], region: "North America" },
    { patient_id: "PT-011", age: 50, sex: "F", bmi: 22.9, condition: "Type 2 Diabetes",  treatment_arm: "Placebo",        baseline_hba1c: 8.3, week12_hba1c: 8.2, reduction: 0.1, adverse_events: 0, discontinued: false, comorbidities: [],                          region: "Asia-Pacific"  },
    { patient_id: "PT-012", age: 42, sex: "M", bmi: 25.6, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (400mg)", baseline_hba1c: 8.6, week12_hba1c: 6.5, reduction: 2.1, adverse_events: 0, discontinued: false, comorbidities: ["Dyslipidaemia"],           region: "Europe"        },
    { patient_id: "PT-013", age: 66, sex: "F", bmi: 31.8, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (200mg)", baseline_hba1c: 9.4, week12_hba1c: 7.6, reduction: 1.8, adverse_events: 2, discontinued: false, comorbidities: ["Hypertension","CKD"],      region: "Latin America" },
    { patient_id: "PT-014", age: 55, sex: "M", bmi: 28.1, condition: "Type 2 Diabetes",  treatment_arm: "Placebo",        baseline_hba1c: 8.8, week12_hba1c: 8.6, reduction: 0.2, adverse_events: 0, discontinued: false, comorbidities: [],                          region: "North America" },
    { patient_id: "PT-015", age: 48, sex: "F", bmi: 26.7, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (400mg)", baseline_hba1c: 8.5, week12_hba1c: 6.4, reduction: 2.1, adverse_events: 1, discontinued: false, comorbidities: ["Hypertension"],            region: "Asia-Pacific"  },
    { patient_id: "PT-016", age: 71, sex: "M", bmi: 30.2, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (200mg)", baseline_hba1c: 9.7, week12_hba1c: 8.0, reduction: 1.7, adverse_events: 4, discontinued: true,  comorbidities: ["Heart Failure","Obesity"],  region: "Europe"        },
    { patient_id: "PT-017", age: 43, sex: "F", bmi: 21.4, condition: "Type 2 Diabetes",  treatment_arm: "Placebo",        baseline_hba1c: 8.2, week12_hba1c: 8.0, reduction: 0.2, adverse_events: 0, discontinued: false, comorbidities: [],                          region: "Asia-Pacific"  },
    { patient_id: "PT-018", age: 59, sex: "M", bmi: 34.1, condition: "Type 2 Diabetes",  treatment_arm: "Drug A (400mg)", baseline_hba1c: 9.0, week12_hba1c: 6.8, reduction: 2.2, adverse_events: 0, discontinued: false, comorbidities: ["Obesity"],                 region: "North America" },
  ],

  // ── Real Estate Listings ──────────────────────────────────────────────────────
  real_estate: [
    { id: "LS-4481", address: "12 Maple Ave",        city: "Austin",       state: "TX", zip: "78701", type: "Single Family", beds: 4, baths: 3,   sqft: 2840, lot_sqft: 7200,  year_built: 2018, list_price: 725000,  price_per_sqft: 255, hoa_monthly: 0,   garage: 2, pool: true,  status: "active",    days_on_market: 12, price_reduced: false, school_rating: 9, walk_score: 62, agent: "Carla Reyes"    },
    { id: "LS-4480", address: "88 Oak Street",       city: "Denver",       state: "CO", zip: "80203", type: "Condo",         beds: 2, baths: 2,   sqft: 1180, lot_sqft: 0,     year_built: 2021, list_price: 498000,  price_per_sqft: 422, hoa_monthly: 420, garage: 1, pool: false, status: "active",    days_on_market: 5,  price_reduced: false, school_rating: 7, walk_score: 88, agent: "Dev Patel"      },
    { id: "LS-4479", address: "340 Riverside Dr",    city: "Nashville",    state: "TN", zip: "37201", type: "Single Family", beds: 3, baths: 2.5, sqft: 2110, lot_sqft: 5800,  year_built: 2005, list_price: 542000,  price_per_sqft: 257, hoa_monthly: 85,  garage: 2, pool: false, status: "pending",   days_on_market: 8,  price_reduced: false, school_rating: 6, walk_score: 74, agent: "Marcus Webb"    },
    { id: "LS-4478", address: "7 Birch Lane",        city: "Portland",     state: "OR", zip: "97201", type: "Townhouse",     beds: 3, baths: 2,   sqft: 1680, lot_sqft: 2100,  year_built: 2016, list_price: 619000,  price_per_sqft: 369, hoa_monthly: 210, garage: 1, pool: false, status: "active",    days_on_market: 22, price_reduced: true,  school_rating: 8, walk_score: 92, agent: "Yuki Tanaka"    },
    { id: "LS-4477", address: "2201 Sunset Blvd",    city: "Los Angeles",  state: "CA", zip: "90028", type: "Condo",         beds: 1, baths: 1,   sqft: 780,  lot_sqft: 0,     year_built: 1998, list_price: 585000,  price_per_sqft: 750, hoa_monthly: 580, garage: 1, pool: true,  status: "active",    days_on_market: 31, price_reduced: true,  school_rating: 5, walk_score: 95, agent: "Sophia Bell"    },
    { id: "LS-4476", address: "54 Elm Court",        city: "Raleigh",      state: "NC", zip: "27601", type: "Single Family", beds: 5, baths: 4,   sqft: 3820, lot_sqft: 10800, year_built: 2022, list_price: 889000,  price_per_sqft: 233, hoa_monthly: 120, garage: 3, pool: true,  status: "active",    days_on_market: 18, price_reduced: false, school_rating: 10,walk_score: 48, agent: "Carla Reyes"    },
    { id: "LS-4475", address: "1 Harbor View",       city: "Miami",        state: "FL", zip: "33101", type: "Condo",         beds: 3, baths: 3,   sqft: 2200, lot_sqft: 0,     year_built: 2019, list_price: 1480000, price_per_sqft: 673, hoa_monthly: 1100,garage: 2, pool: true,  status: "active",    days_on_market: 44, price_reduced: false, school_rating: 6, walk_score: 82, agent: "Jorge Ruiz"     },
    { id: "LS-4474", address: "930 Pine Ridge Rd",   city: "Charlotte",    state: "NC", zip: "28201", type: "Single Family", beds: 4, baths: 3,   sqft: 2640, lot_sqft: 8400,  year_built: 2014, list_price: 488000,  price_per_sqft: 185, hoa_monthly: 0,   garage: 2, pool: false, status: "sold",      days_on_market: 6,  price_reduced: false, school_rating: 8, walk_score: 55, agent: "Marcus Webb"    },
    { id: "LS-4473", address: "22 W 34th St #8F",    city: "New York",     state: "NY", zip: "10001", type: "Co-op",         beds: 2, baths: 1,   sqft: 950,  lot_sqft: 0,     year_built: 1962, list_price: 849000,  price_per_sqft: 894, hoa_monthly: 1840,garage: 0, pool: false, status: "active",    days_on_market: 62, price_reduced: true,  school_rating: 7, walk_score: 99, agent: "Nadia Cohen"    },
    { id: "LS-4472", address: "418 Magnolia Way",    city: "Atlanta",      state: "GA", zip: "30301", type: "Single Family", beds: 4, baths: 3.5, sqft: 3100, lot_sqft: 9600,  year_built: 2008, list_price: 598000,  price_per_sqft: 193, hoa_monthly: 0,   garage: 2, pool: true,  status: "pending",   days_on_market: 4,  price_reduced: false, school_rating: 7, walk_score: 68, agent: "Jorge Ruiz"     },
    { id: "LS-4471", address: "77 Lakeside Dr",      city: "Minneapolis",  state: "MN", zip: "55401", type: "Single Family", beds: 3, baths: 2,   sqft: 1920, lot_sqft: 6800,  year_built: 1991, list_price: 398000,  price_per_sqft: 207, hoa_monthly: 0,   garage: 2, pool: false, status: "active",    days_on_market: 38, price_reduced: true,  school_rating: 9, walk_score: 72, agent: "Dev Patel"      },
    { id: "LS-4470", address: "612 Congress Ave",    city: "Austin",       state: "TX", zip: "78701", type: "Townhouse",     beds: 3, baths: 2.5, sqft: 1980, lot_sqft: 3200,  year_built: 2020, list_price: 668000,  price_per_sqft: 337, hoa_monthly: 175, garage: 2, pool: false, status: "active",    days_on_market: 9,  price_reduced: false, school_rating: 8, walk_score: 89, agent: "Carla Reyes"    },
    { id: "LS-4469", address: "5 Seacliff Terrace",  city: "San Francisco",state: "CA", zip: "94121", type: "Single Family", beds: 5, baths: 4,   sqft: 4100, lot_sqft: 5400,  year_built: 1928, list_price: 3200000, price_per_sqft: 780, hoa_monthly: 0,   garage: 2, pool: false, status: "active",    days_on_market: 28, price_reduced: false, school_rating: 8, walk_score: 87, agent: "Sophia Bell"    },
    { id: "LS-4468", address: "820 Peachtree NE",    city: "Atlanta",      state: "GA", zip: "30309", type: "Condo",         beds: 1, baths: 1,   sqft: 840,  lot_sqft: 0,     year_built: 2017, list_price: 298000,  price_per_sqft: 355, hoa_monthly: 380, garage: 1, pool: true,  status: "sold",      days_on_market: 3,  price_reduced: false, school_rating: 6, walk_score: 91, agent: "Jorge Ruiz"     },
    { id: "LS-4467", address: "3 Countryside Ln",    city: "Phoenix",      state: "AZ", zip: "85001", type: "Single Family", beds: 4, baths: 2,   sqft: 2280, lot_sqft: 12000, year_built: 2002, list_price: 448000,  price_per_sqft: 197, hoa_monthly: 60,  garage: 3, pool: true,  status: "active",    days_on_market: 54, price_reduced: true,  school_rating: 5, walk_score: 38, agent: "Nadia Cohen"    },
  ],

  // ── IoT Sensor Readings ───────────────────────────────────────────────────────
  iot_sensors: [
    { sensor_id: "S-101", location: "Factory Floor A", type: "temperature_c",   value: 41.2,  unit: "°C",  timestamp: "2026-03-21T08:00:00Z", status: "warning", threshold_hi: 40,  threshold_lo: 15,  battery_pct: 88, firmware: "v2.4.1" },
    { sensor_id: "S-102", location: "Factory Floor A", type: "vibration_mm_s",  value: 3.8,   unit: "mm/s",timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 10,  threshold_lo: 0,   battery_pct: 91, firmware: "v2.4.1" },
    { sensor_id: "S-103", location: "Cooling Unit 1",  type: "temperature_c",   value: 6.1,   unit: "°C",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 8,   threshold_lo: 2,   battery_pct: 74, firmware: "v2.3.9" },
    { sensor_id: "S-104", location: "Cooling Unit 1",  type: "humidity_pct",    value: 78.4,  unit: "%",   timestamp: "2026-03-21T08:00:00Z", status: "warning", threshold_hi: 75,  threshold_lo: 30,  battery_pct: 74, firmware: "v2.3.9" },
    { sensor_id: "S-105", location: "Server Room",     type: "temperature_c",   value: 22.8,  unit: "°C",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 27,  threshold_lo: 18,  battery_pct: 100,firmware: "v2.4.1" },
    { sensor_id: "S-106", location: "Server Room",     type: "humidity_pct",    value: 44.2,  unit: "%",   timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 60,  threshold_lo: 30,  battery_pct: 100,firmware: "v2.4.1" },
    { sensor_id: "S-107", location: "Warehouse Gate",  type: "motion_count",    value: 142,   unit: "events/hr",timestamp: "2026-03-21T08:00:00Z", status: "ok", threshold_hi: 500, threshold_lo: 0,   battery_pct: 62, firmware: "v2.2.0" },
    { sensor_id: "S-108", location: "Boiler Room",     type: "pressure_bar",    value: 8.9,   unit: "bar", timestamp: "2026-03-21T08:00:00Z", status: "critical",threshold_hi: 8.5, threshold_lo: 2.0, battery_pct: 55, firmware: "v2.1.8" },
    { sensor_id: "S-109", location: "Boiler Room",     type: "temperature_c",   value: 88.4,  unit: "°C",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 95,  threshold_lo: 60,  battery_pct: 55, firmware: "v2.1.8" },
    { sensor_id: "S-110", location: "Roof HVAC",       type: "power_kw",        value: 12.4,  unit: "kW",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 20,  threshold_lo: 0,   battery_pct: null,firmware: "v2.4.0"},
    { sensor_id: "S-111", location: "Production Line 2",type: "co2_ppm",        value: 1420,  unit: "ppm", timestamp: "2026-03-21T08:00:00Z", status: "warning", threshold_hi: 1200,threshold_lo: 400, battery_pct: 81, firmware: "v2.4.1" },
    { sensor_id: "S-112", location: "Assembly Area",   type: "noise_db",        value: 82.1,  unit: "dB",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 85,  threshold_lo: 0,   battery_pct: 90, firmware: "v2.3.9" },
    { sensor_id: "S-113", location: "Water Treatment", type: "ph_level",        value: 6.8,   unit: "pH",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 8.5, threshold_lo: 6.5, battery_pct: 48, firmware: "v2.0.5" },
    { sensor_id: "S-114", location: "Water Treatment", type: "flow_l_per_min",  value: 284.0, unit: "L/min",timestamp:"2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 400, threshold_lo: 100, battery_pct: 48, firmware: "v2.0.5" },
    { sensor_id: "S-115", location: "Parking Lot",     type: "ambient_lux",     value: 8400,  unit: "lux", timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 100000,threshold_lo: 0, battery_pct: 95, firmware: "v2.4.1" },
    { sensor_id: "S-116", location: "Cold Storage B",  type: "temperature_c",   value: -18.6, unit: "°C",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: -15, threshold_lo: -25, battery_pct: 84, firmware: "v2.3.9" },
    { sensor_id: "S-117", location: "Factory Floor B", type: "vibration_mm_s",  value: 14.2,  unit: "mm/s",timestamp: "2026-03-21T08:00:00Z", status: "critical",threshold_hi: 10,  threshold_lo: 0,   battery_pct: 77, firmware: "v2.4.0" },
    { sensor_id: "S-118", location: "Electrical Room", type: "voltage_v",       value: 228.4, unit: "V",   timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 240, threshold_lo: 210, battery_pct: null,firmware: "v2.4.1"},
    { sensor_id: "S-119", location: "Electrical Room", type: "current_a",       value: 84.2,  unit: "A",   timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 100, threshold_lo: 0,   battery_pct: null,firmware: "v2.4.1"},
    { sensor_id: "S-120", location: "Roof Solar Array","type": "power_output_kw",value: 48.2, unit: "kW",  timestamp: "2026-03-21T08:00:00Z", status: "ok",      threshold_hi: 60,  threshold_lo: 0,   battery_pct: null,firmware: "v1.8.2"},
  ],

  // ── Equity Portfolio ──────────────────────────────────────────────────────────
  portfolio: [
    { ticker: "AAPL",  name: "Apple Inc.",                  sector: "Technology",       shares: 420,  avg_cost: 148.22, current_price: 192.40, market_value: 80808,  unrealized_pnl: 18564, pnl_pct: 29.8,  weight_pct: 14.2, beta: 1.24, pe_ratio: 31.2, dividend_yield: 0.52, analyst_rating: "Buy",      week52_hi: 199.62, week52_lo: 164.08, ytd_return: 12.4  },
    { ticker: "MSFT",  name: "Microsoft Corp.",             sector: "Technology",       shares: 180,  avg_cost: 302.10, current_price: 418.55, market_value: 75339,  unrealized_pnl: 20961, pnl_pct: 38.5,  weight_pct: 13.2, beta: 0.90, pe_ratio: 35.8, dividend_yield: 0.72, analyst_rating: "Buy",      week52_hi: 420.82, week52_lo: 362.90, ytd_return: 8.1   },
    { ticker: "NVDA",  name: "NVIDIA Corp.",                sector: "Semiconductors",   shares: 95,   avg_cost: 412.80, current_price: 875.40, market_value: 83163,  unrealized_pnl: 43929, pnl_pct: 112.0, weight_pct: 14.6, beta: 1.72, pe_ratio: 68.4, dividend_yield: 0.03, analyst_rating: "Buy",      week52_hi: 974.00, week52_lo: 560.50, ytd_return: 82.1  },
    { ticker: "JPM",   name: "JPMorgan Chase",              sector: "Financials",       shares: 340,  avg_cost: 144.50, current_price: 198.80, market_value: 67592,  unrealized_pnl: 18462, pnl_pct: 37.6,  weight_pct: 11.9, beta: 1.12, pe_ratio: 12.1, dividend_yield: 2.21, analyst_rating: "Buy",      week52_hi: 205.88, week52_lo: 162.44, ytd_return: 18.8  },
    { ticker: "UNH",   name: "UnitedHealth Group",          sector: "Healthcare",       shares: 88,   avg_cost: 480.20, current_price: 522.10, market_value: 45945,  unrealized_pnl: 3687,  pnl_pct: 8.7,   weight_pct: 8.1,  beta: 0.58, pe_ratio: 21.4, dividend_yield: 1.48, analyst_rating: "Hold",     week52_hi: 581.22, week52_lo: 446.80, ytd_return: -4.2  },
    { ticker: "V",     name: "Visa Inc.",                   sector: "Financials",       shares: 210,  avg_cost: 212.40, current_price: 278.90, market_value: 58569,  unrealized_pnl: 13965, pnl_pct: 31.3,  weight_pct: 10.3, beta: 0.94, pe_ratio: 28.8, dividend_yield: 0.77, analyst_rating: "Buy",      week52_hi: 285.00, week52_lo: 220.14, ytd_return: 9.4   },
    { ticker: "AMZN",  name: "Amazon.com Inc.",             sector: "Consumer Cyclical", shares: 310, avg_cost: 138.80, current_price: 182.10, market_value: 56451,  unrealized_pnl: 13423, pnl_pct: 31.2,  weight_pct: 9.9,  beta: 1.38, pe_ratio: 58.2, dividend_yield: 0.0,  analyst_rating: "Buy",      week52_hi: 201.20, week52_lo: 151.61, ytd_return: 14.8  },
    { ticker: "XOM",   name: "Exxon Mobil Corp.",           sector: "Energy",           shares: 480,  avg_cost: 96.20,  current_price: 108.40, market_value: 52032,  unrealized_pnl: 5856,  pnl_pct: 12.7,  weight_pct: 9.1,  beta: 0.80, pe_ratio: 14.8, dividend_yield: 3.42, analyst_rating: "Hold",     week52_hi: 123.75, week52_lo: 94.20,  ytd_return: -5.8  },
    { ticker: "LLY",   name: "Eli Lilly & Co.",             sector: "Healthcare",       shares: 52,   avg_cost: 421.00, current_price: 798.20, market_value: 41506,  unrealized_pnl: 19610, pnl_pct: 89.6,  weight_pct: 7.3,  beta: 0.42, pe_ratio: 112.0,dividend_yield: 0.64, analyst_rating: "Buy",      week52_hi: 972.00, week52_lo: 620.40, ytd_return: 68.2  },
    { ticker: "TSLA",  name: "Tesla Inc.",                  sector: "Consumer Cyclical", shares: 140, avg_cost: 248.10, current_price: 176.50, market_value: 24710,  unrealized_pnl: -10024,pnl_pct: -28.9, weight_pct: 4.3,  beta: 2.18, pe_ratio: 48.2, dividend_yield: 0.0,  analyst_rating: "Hold",     week52_hi: 299.29, week52_lo: 138.80, ytd_return: -31.4 },
    { ticker: "BRK.B", name: "Berkshire Hathaway B",        sector: "Financials",       shares: 128,  avg_cost: 296.40, current_price: 388.10, market_value: 49677,  unrealized_pnl: 11738, pnl_pct: 30.9,  weight_pct: 8.7,  beta: 0.88, pe_ratio: 22.4, dividend_yield: 0.0,  analyst_rating: "Buy",      week52_hi: 408.80, week52_lo: 322.14, ytd_return: 16.4  },
  ],

  // ── Restaurant / Food & Beverage ─────────────────────────────────────────────
  restaurant_orders: [
    { order_id: "R-8821", date: "2026-03-21", time: "12:14", table: 7,  server: "Maria L.", covers: 3, channel: "dine-in",  items: ["Grilled Salmon","Caesar Salad","Pasta Carbonara"], subtotal: 88.50,  tax: 7.97,  tip: 15.93, total: 112.40, payment: "card",  special_requests: "gluten-free pasta", kitchen_time_min: 22, rating: 5 },
    { order_id: "R-8820", date: "2026-03-21", time: "12:08", table: 12, server: "James K.", covers: 2, channel: "dine-in",  items: ["Margherita Pizza","House Salad","Tiramisu"],        subtotal: 54.00,  tax: 4.86,  tip: 10.80, total: 69.66,  payment: "card",  special_requests: null,                kitchen_time_min: 18, rating: 4 },
    { order_id: "R-8819", date: "2026-03-21", time: "11:55", table: null,server: null,      covers: 1, channel: "delivery", items: ["Burger & Fries","Chocolate Shake"],                 subtotal: 29.50,  tax: 2.66,  tip: 5.90,  total: 38.06,  payment: "app",   special_requests: "extra ketchup",     kitchen_time_min: 14, rating: 4 },
    { order_id: "R-8818", date: "2026-03-21", time: "11:42", table: 3,  server: "Ana P.",   covers: 4, channel: "dine-in",  items: ["Ribeye 12oz","Lobster Bisque","Truffle Fries","Cheesecake x2"], subtotal: 198.00, tax: 17.82, tip: 39.60, total: 255.42, payment: "card", special_requests: "medium-rare steak", kitchen_time_min: 32, rating: 5 },
    { order_id: "R-8817", date: "2026-03-21", time: "11:30", table: null,server: null,      covers: 1, channel: "pickup",   items: ["Chicken Wrap","Lemonade"],                          subtotal: 18.50,  tax: 1.67,  tip: 0,     total: 20.17,  payment: "cash",  special_requests: null,                kitchen_time_min: 10, rating: 3 },
    { order_id: "R-8816", date: "2026-03-20", time: "19:48", table: 8,  server: "James K.", covers: 6, channel: "dine-in",  items: ["Seafood Platter","Bruschetta x2","Wine Bottle x2","Panna Cotta x2"], subtotal: 312.00, tax: 28.08, tip: 62.40, total: 402.48, payment: "card", special_requests: "anniversary dinner, add candle", kitchen_time_min: 38, rating: 5 },
    { order_id: "R-8815", date: "2026-03-20", time: "19:22", table: 15, server: "Maria L.", covers: 2, channel: "dine-in",  items: ["Veggie Burger","Falafel Bowl"],                     subtotal: 42.00,  tax: 3.78,  tip: 8.40,  total: 54.18,  payment: "card",  special_requests: "vegan, no dairy",   kitchen_time_min: 20, rating: 4 },
    { order_id: "R-8814", date: "2026-03-20", time: "18:55", table: null,server: null,      covers: 2, channel: "delivery", items: ["Pepperoni Pizza Large","Garlic Bread","Tiramisu"],   subtotal: 58.00,  tax: 5.22,  tip: 11.60, total: 74.82,  payment: "app",   special_requests: null,                kitchen_time_min: 25, rating: 2 },
    { order_id: "R-8813", date: "2026-03-20", time: "13:10", table: 5,  server: "Ana P.",   covers: 1, channel: "dine-in",  items: ["Club Sandwich","Tomato Soup","Iced Tea"],            subtotal: 32.50,  tax: 2.93,  tip: 6.50,  total: 41.93,  payment: "cash",  special_requests: null,                kitchen_time_min: 16, rating: 4 },
    { order_id: "R-8812", date: "2026-03-20", time: "12:44", table: 10, server: "James K.", covers: 5, channel: "dine-in",  items: ["Pasta Primavera x2","Chicken Piccata","Minestrone x2","Cannoli x2"], subtotal: 124.00, tax: 11.16, tip: 24.80, total: 159.96, payment: "card", special_requests: "nut allergy table",  kitchen_time_min: 28, rating: 5 },
    { order_id: "R-8811", date: "2026-03-20", time: "12:15", table: null,server: null,      covers: 3, channel: "pickup",   items: ["3x Sushi Rolls","Miso Soup x2","Edamame"],          subtotal: 72.00,  tax: 6.48,  tip: 0,     total: 78.48,  payment: "app",   special_requests: "chopsticks only",   kitchen_time_min: 18, rating: 5 },
    { order_id: "R-8810", date: "2026-03-19", time: "20:30", table: 2,  server: "Maria L.", covers: 2, channel: "dine-in",  items: ["Duck Confit","Beet Salad","Crème Brûlée"],           subtotal: 97.00,  tax: 8.73,  tip: 19.40, total: 125.13, payment: "card",  special_requests: null,                kitchen_time_min: 35, rating: 4 },
    { order_id: "R-8809", date: "2026-03-19", time: "13:00", table: null,server: null,      covers: 1, channel: "delivery", items: ["Acai Bowl","Cold Brew"],                            subtotal: 22.00,  tax: 1.98,  tip: 4.40,  total: 28.38,  payment: "app",   special_requests: "no banana",         kitchen_time_min: 8,  rating: 5 },
  ],

  // ── Student Performance ───────────────────────────────────────────────────────
  student_performance: [
    { student_id: "S001", name: "Aaliya Khan",      grade: 11, school: "Lincoln High",  gpa: 3.92, sat_score: 1480, act_score: 33, attendance_pct: 98, extracurriculars: ["Debate","Chess","Violin"],          ap_courses: 4, volunteer_hrs: 120, intended_major: "Pre-Med",      college_acceptance: "UC Berkeley",      financial_aid: true,  first_gen: false },
    { student_id: "S002", name: "Marcus Dupont",    grade: 12, school: "Jefferson Prep",gpa: 3.41, sat_score: 1290, act_score: 28, attendance_pct: 92, extracurriculars: ["Football","Band"],                  ap_courses: 2, volunteer_hrs: 40,  intended_major: "Business",      college_acceptance: "Ohio State",        financial_aid: false, first_gen: false },
    { student_id: "S003", name: "Priya Nair",       grade: 12, school: "Lincoln High",  gpa: 4.00, sat_score: 1560, act_score: 35, attendance_pct: 99, extracurriculars: ["Math League","Science Bowl","NHS"],  ap_courses: 7, volunteer_hrs: 200, intended_major: "Computer Science",college_acceptance: "MIT",               financial_aid: true,  first_gen: true  },
    { student_id: "S004", name: "Diego Reyes",      grade: 10, school: "Westview Academy",gpa:3.15, sat_score: null, act_score: null,attendance_pct: 88, extracurriculars: ["Soccer","Drama"],                 ap_courses: 1, volunteer_hrs: 25,  intended_major: "Undecided",     college_acceptance: null,                financial_aid: true,  first_gen: true  },
    { student_id: "S005", name: "Emma Chen",        grade: 11, school: "Jefferson Prep",gpa: 3.78, sat_score: 1410, act_score: 31, attendance_pct: 96, extracurriculars: ["Swim Team","Yearbook","Key Club"],  ap_courses: 3, volunteer_hrs: 85,  intended_major: "Psychology",    college_acceptance: null,                financial_aid: false, first_gen: false },
    { student_id: "S006", name: "Jaylen Brooks",    grade: 12, school: "Westview Academy",gpa:2.88, sat_score: 1120, act_score: 24, attendance_pct: 81, extracurriculars: ["Basketball"],                    ap_courses: 0, volunteer_hrs: 15,  intended_major: "Criminal Justice",college_acceptance: "Local Community",   financial_aid: true,  first_gen: true  },
    { student_id: "S007", name: "Sophie Lambert",   grade: 11, school: "Lincoln High",  gpa: 3.55, sat_score: 1340, act_score: 29, attendance_pct: 94, extracurriculars: ["Theatre","French Club"],            ap_courses: 2, volunteer_hrs: 60,  intended_major: "Journalism",    college_acceptance: null,                financial_aid: false, first_gen: false },
    { student_id: "S008", name: "Ethan Patel",      grade: 12, school: "Lincoln High",  gpa: 3.88, sat_score: 1500, act_score: 34, attendance_pct: 97, extracurriculars: ["Robotics","Science Bowl","DECA"],   ap_courses: 5, volunteer_hrs: 140, intended_major: "Mechanical Eng.",college_acceptance: "Georgia Tech",     financial_aid: true,  first_gen: true  },
    { student_id: "S009", name: "Zoe Williams",     grade: 10, school: "Jefferson Prep",gpa: 3.62, sat_score: null, act_score: null,attendance_pct: 95, extracurriculars: ["Orchestra","Debate"],              ap_courses: 2, volunteer_hrs: 50,  intended_major: "Music",         college_acceptance: null,                financial_aid: false, first_gen: false },
    { student_id: "S010", name: "Carlos Mendez",    grade: 12, school: "Westview Academy",gpa:3.22, sat_score: 1240, act_score: 27, attendance_pct: 90, extracurriculars: ["Baseball","ROTC"],                ap_courses: 1, volunteer_hrs: 80,  intended_major: "Military/Eng.",  college_acceptance: "West Point (pending)",financial_aid: false,first_gen: false },
    { student_id: "S011", name: "Fatima Al-Rashid", grade: 11, school: "Lincoln High",  gpa: 3.96, sat_score: 1520, act_score: 34, attendance_pct: 99, extracurriculars: ["Model UN","NHS","Tennis"],          ap_courses: 6, volunteer_hrs: 180, intended_major: "International Law",college_acceptance: null,               financial_aid: true,  first_gen: true  },
    { student_id: "S012", name: "Tyler Johnson",    grade: 10, school: "Westview Academy",gpa:2.50, sat_score: null, act_score: null,attendance_pct: 74, extracurriculars: ["Gaming Club"],                   ap_courses: 0, volunteer_hrs: 0,   intended_major: "Undecided",     college_acceptance: null,                financial_aid: true,  first_gen: false },
    { student_id: "S013", name: "Isabella Rossi",   grade: 12, school: "Jefferson Prep",gpa: 3.68, sat_score: 1380, act_score: 30, attendance_pct: 93, extracurriculars: ["Art Club","Italian Club","Tennis"],  ap_courses: 3, volunteer_hrs: 70,  intended_major: "Architecture",  college_acceptance: "RISD",              financial_aid: false, first_gen: false },
    { student_id: "S014", name: "Aiden Park",       grade: 11, school: "Lincoln High",  gpa: 3.44, sat_score: 1310, act_score: 28, attendance_pct: 91, extracurriculars: ["Taekwondo","Code Club"],            ap_courses: 2, volunteer_hrs: 35,  intended_major: "Computer Science",college_acceptance: null,               financial_aid: false, first_gen: false },
    { student_id: "S015", name: "Amara Osei",       grade: 12, school: "Westview Academy",gpa:3.80, sat_score: 1450, act_score: 32, attendance_pct: 98, extracurriculars: ["Track","NHS","Peer Tutoring"],    ap_courses: 4, volunteer_hrs: 160, intended_major: "Nursing",       college_acceptance: "UNC Chapel Hill",   financial_aid: true,  first_gen: true  },
  ],

  // ── Sports: Premier League Season Stats ──────────────────────────────────────
  premier_league: [
    { club: "Manchester City",    played: 30, won: 22, drawn: 4, lost: 4, goals_for: 74, goals_against: 32, goal_diff: 42, points: 70, form: "WWWDW", top_scorer: "Haaland",    goals: 28, xg_for: 72.4, xg_against: 28.1, avg_possession: 62.4, shots_pg: 16.8, clean_sheets: 12, position: 1  },
    { club: "Arsenal",            played: 30, won: 21, drawn: 5, lost: 4, goals_for: 68, goals_against: 28, goal_diff: 40, points: 68, form: "WDWWW", top_scorer: "Saka",       goals: 18, xg_for: 65.8, xg_against: 30.2, avg_possession: 58.1, shots_pg: 15.2, clean_sheets: 14, position: 2  },
    { club: "Liverpool",          played: 30, won: 20, drawn: 6, lost: 4, goals_for: 72, goals_against: 38, goal_diff: 34, points: 66, form: "WWWLW", top_scorer: "Salah",      goals: 22, xg_for: 68.4, xg_against: 38.8, avg_possession: 56.2, shots_pg: 17.1, clean_sheets: 9,  position: 3  },
    { club: "Chelsea",            played: 30, won: 16, drawn: 7, lost: 7, goals_for: 58, goals_against: 44, goal_diff: 14, points: 55, form: "WDLDW", top_scorer: "Palmer",     goals: 20, xg_for: 54.2, xg_against: 46.1, avg_possession: 54.8, shots_pg: 14.4, clean_sheets: 8,  position: 4  },
    { club: "Aston Villa",        played: 30, won: 15, drawn: 6, lost: 9, goals_for: 60, goals_against: 48, goal_diff: 12, points: 51, form: "LWWDL", top_scorer: "Watkins",    goals: 16, xg_for: 55.8, xg_against: 50.2, avg_possession: 50.4, shots_pg: 13.8, clean_sheets: 7,  position: 5  },
    { club: "Tottenham Hotspur",  played: 30, won: 14, drawn: 5, lost: 11,goals_for: 55, goals_against: 52, goal_diff: 3,  points: 47, form: "LWDWL", top_scorer: "Son",        goals: 14, xg_for: 51.4, xg_against: 53.8, avg_possession: 52.1, shots_pg: 13.2, clean_sheets: 6,  position: 6  },
    { club: "Newcastle United",   played: 30, won: 13, drawn: 7, lost: 10,goals_for: 52, goals_against: 48, goal_diff: 4,  points: 46, form: "DWWLD", top_scorer: "Isak",       goals: 19, xg_for: 48.8, xg_against: 49.4, avg_possession: 48.8, shots_pg: 12.8, clean_sheets: 8,  position: 7  },
    { club: "Manchester United",  played: 30, won: 12, drawn: 6, lost: 12,goals_for: 38, goals_against: 46, goal_diff: -8, points: 42, form: "LLDWL", top_scorer: "Rashford",   goals: 8,  xg_for: 40.2, xg_against: 48.8, avg_possession: 48.2, shots_pg: 11.8, clean_sheets: 7,  position: 8  },
    { club: "Brighton",           played: 30, won: 11, drawn: 8, lost: 11,goals_for: 50, goals_against: 52, goal_diff: -2, points: 41, form: "DWLDW", top_scorer: "Welbeck",    goals: 11, xg_for: 52.4, xg_against: 50.8, avg_possession: 55.8, shots_pg: 14.8, clean_sheets: 5,  position: 9  },
    { club: "West Ham United",    played: 30, won: 10, drawn: 6, lost: 14,goals_for: 42, goals_against: 58, goal_diff: -16,points: 36, form: "LLDLW", top_scorer: "Kudus",      goals: 12, xg_for: 44.8, xg_against: 60.2, avg_possession: 46.4, shots_pg: 11.4, clean_sheets: 4,  position: 10 },
    { club: "Wolverhampton",      played: 30, won: 8,  drawn: 7, lost: 15,goals_for: 36, goals_against: 60, goal_diff: -24,points: 31, form: "DLWLL", top_scorer: "Strand Larsen",goals: 10,xg_for: 38.4, xg_against: 62.1, avg_possession: 44.2, shots_pg: 10.8, clean_sheets: 4,  position: 11 },
    { club: "Fulham",             played: 30, won: 8,  drawn: 6, lost: 16,goals_for: 38, goals_against: 62, goal_diff: -24,points: 30, form: "LWLLL", top_scorer: "Jiménez",    goals: 9,  xg_for: 40.8, xg_against: 63.4, avg_possession: 47.8, shots_pg: 11.2, clean_sheets: 5,  position: 12 },
    { club: "Brentford",          played: 30, won: 8,  drawn: 5, lost: 17,goals_for: 40, goals_against: 64, goal_diff: -24,points: 29, form: "WLLLD", top_scorer: "Mbeumo",     goals: 13, xg_for: 42.1, xg_against: 66.2, avg_possession: 43.4, shots_pg: 12.4, clean_sheets: 3,  position: 13 },
    { club: "Crystal Palace",     played: 30, won: 7,  drawn: 7, lost: 16,goals_for: 30, goals_against: 52, goal_diff: -22,points: 28, form: "LDLWL", top_scorer: "Eze",        goals: 8,  xg_for: 32.4, xg_against: 54.8, avg_possession: 42.2, shots_pg: 9.8,  clean_sheets: 6,  position: 14 },
    { club: "Everton",            played: 30, won: 6,  drawn: 9, lost: 15,goals_for: 28, goals_against: 50, goal_diff: -22,points: 27, form: "DLDLD", top_scorer: "Calvert-Lewin",goals: 7,xg_for: 30.8, xg_against: 52.1, avg_possession: 43.8, shots_pg: 10.2, clean_sheets: 5,  position: 15 },
    { club: "Nottm Forest",       played: 30, won: 6,  drawn: 8, lost: 16,goals_for: 30, goals_against: 55, goal_diff: -25,points: 26, form: "LDLLD", top_scorer: "Awoniyi",    goals: 6,  xg_for: 28.4, xg_against: 56.8, avg_possession: 40.2, shots_pg: 9.4,  clean_sheets: 4,  position: 16 },
    { club: "Burnley",            played: 30, won: 4,  drawn: 6, lost: 20,goals_for: 24, goals_against: 72, goal_diff: -48,points: 18, form: "LLLLD", top_scorer: "Zeki Amdouni",goals: 5, xg_for: 26.8, xg_against: 74.2, avg_possession: 38.4, shots_pg: 8.8,  clean_sheets: 2,  position: 17 },
    { club: "Sheffield United",   played: 30, won: 3,  drawn: 4, lost: 23,goals_for: 18, goals_against: 80, goal_diff: -62,points: 13, form: "LLLLL", top_scorer: "McBurnie",   goals: 4,  xg_for: 22.4, xg_against: 82.1, avg_possession: 36.8, shots_pg: 7.8,  clean_sheets: 1,  position: 18 },
    { club: "Luton Town",         played: 30, won: 3,  drawn: 4, lost: 23,goals_for: 20, goals_against: 78, goal_diff: -58,points: 13, form: "LLLWL", top_scorer: "Elijah Adebayo",goals: 6,xg_for: 24.8, xg_against: 79.4, avg_possession: 37.2, shots_pg: 8.2,  clean_sheets: 2,  position: 19 },
    { club: "Burnley",            played: 30, won: 2,  drawn: 6, lost: 22,goals_for: 22, goals_against: 76, goal_diff: -54,points: 12, form: "DLLLL", top_scorer: "Anass Zaroury",goals: 4, xg_for: 24.1, xg_against: 78.8, avg_possession: 36.2, shots_pg: 7.4,  clean_sheets: 1,  position: 20 },
  ],

  // ── Global Country Development Indicators ────────────────────────────────────
  country_indicators: [
    { country: "United States",    iso: "US", region: "North America",    gdp_per_capita: 76399, hdi: 0.926, life_expectancy: 78.9, literacy_rate: 99,   internet_pct: 92,  co2_per_capita: 14.2, pop_millions: 335.0, urban_pct: 83, gini: 41.5, health_exp_gdp_pct: 17.1 },
    { country: "China",            iso: "CN", region: "East Asia",        gdp_per_capita: 12720, hdi: 0.788, life_expectancy: 78.2, literacy_rate: 97,   internet_pct: 73,  co2_per_capita: 8.0,  pop_millions: 1412.0,urban_pct: 65, gini: 38.2, health_exp_gdp_pct: 5.4  },
    { country: "Germany",          iso: "DE", region: "Europe",           gdp_per_capita: 48432, hdi: 0.942, life_expectancy: 81.1, literacy_rate: 99,   internet_pct: 94,  co2_per_capita: 8.1,  pop_millions: 84.1,  urban_pct: 77, gini: 31.7, health_exp_gdp_pct: 12.7 },
    { country: "India",            iso: "IN", region: "South Asia",       gdp_per_capita: 2389,  hdi: 0.644, life_expectancy: 70.8, literacy_rate: 74,   internet_pct: 52,  co2_per_capita: 2.0,  pop_millions: 1429.0,urban_pct: 36, gini: 35.7, health_exp_gdp_pct: 3.3  },
    { country: "Brazil",           iso: "BR", region: "South America",    gdp_per_capita: 8917,  hdi: 0.760, life_expectancy: 75.5, literacy_rate: 94,   internet_pct: 81,  co2_per_capita: 2.3,  pop_millions: 215.3, urban_pct: 88, gini: 52.9, health_exp_gdp_pct: 9.6  },
    { country: "Japan",            iso: "JP", region: "East Asia",        gdp_per_capita: 33820, hdi: 0.920, life_expectancy: 84.3, literacy_rate: 99,   internet_pct: 93,  co2_per_capita: 8.5,  pop_millions: 124.5, urban_pct: 92, gini: 32.9, health_exp_gdp_pct: 10.9 },
    { country: "Nigeria",          iso: "NG", region: "Sub-Saharan Africa",gdp_per_capita: 2184, hdi: 0.535, life_expectancy: 63.0, literacy_rate: 62,   internet_pct: 55,  co2_per_capita: 0.6,  pop_millions: 222.0, urban_pct: 54, gini: 43.0, health_exp_gdp_pct: 3.9  },
    { country: "United Kingdom",   iso: "GB", region: "Europe",           gdp_per_capita: 45850, hdi: 0.940, life_expectancy: 81.3, literacy_rate: 99,   internet_pct: 96,  co2_per_capita: 5.3,  pop_millions: 67.7,  urban_pct: 84, gini: 35.1, health_exp_gdp_pct: 11.9 },
    { country: "France",           iso: "FR", region: "Europe",           gdp_per_capita: 42330, hdi: 0.910, life_expectancy: 82.7, literacy_rate: 99,   internet_pct: 92,  co2_per_capita: 5.2,  pop_millions: 68.0,  urban_pct: 81, gini: 32.4, health_exp_gdp_pct: 11.9 },
    { country: "South Africa",     iso: "ZA", region: "Sub-Saharan Africa",gdp_per_capita: 6001, hdi: 0.713, life_expectancy: 65.5, literacy_rate: 87,   internet_pct: 72,  co2_per_capita: 6.8,  pop_millions: 60.0,  urban_pct: 68, gini: 63.0, health_exp_gdp_pct: 8.5  },
    { country: "Canada",           iso: "CA", region: "North America",    gdp_per_capita: 52962, hdi: 0.936, life_expectancy: 82.3, literacy_rate: 99,   internet_pct: 93,  co2_per_capita: 14.2, pop_millions: 38.2,  urban_pct: 82, gini: 33.3, health_exp_gdp_pct: 12.2 },
    { country: "Australia",        iso: "AU", region: "Oceania",          gdp_per_capita: 64812, hdi: 0.951, life_expectancy: 83.3, literacy_rate: 99,   internet_pct: 96,  co2_per_capita: 15.4, pop_millions: 26.1,  urban_pct: 87, gini: 34.3, health_exp_gdp_pct: 9.6  },
    { country: "Mexico",           iso: "MX", region: "North America",    gdp_per_capita: 10046, hdi: 0.758, life_expectancy: 75.0, literacy_rate: 95,   internet_pct: 76,  co2_per_capita: 3.9,  pop_millions: 128.5, urban_pct: 81, gini: 45.4, health_exp_gdp_pct: 5.5  },
    { country: "Indonesia",        iso: "ID", region: "Southeast Asia",   gdp_per_capita: 4580,  hdi: 0.705, life_expectancy: 71.7, literacy_rate: 96,   internet_pct: 77,  co2_per_capita: 2.2,  pop_millions: 275.5, urban_pct: 58, gini: 38.2, health_exp_gdp_pct: 3.5  },
    { country: "Saudi Arabia",     iso: "SA", region: "Middle East",      gdp_per_capita: 23185, hdi: 0.875, life_expectancy: 76.5, literacy_rate: 98,   internet_pct: 95,  co2_per_capita: 19.3, pop_millions: 36.0,  urban_pct: 84, gini: 45.9, health_exp_gdp_pct: 5.3  },
    { country: "Sweden",           iso: "SE", region: "Europe",           gdp_per_capita: 55216, hdi: 0.947, life_expectancy: 83.1, literacy_rate: 99,   internet_pct: 97,  co2_per_capita: 3.8,  pop_millions: 10.5,  urban_pct: 88, gini: 27.6, health_exp_gdp_pct: 11.0 },
    { country: "Pakistan",         iso: "PK", region: "South Asia",       gdp_per_capita: 1505,  hdi: 0.540, life_expectancy: 67.2, literacy_rate: 58,   internet_pct: 36,  co2_per_capita: 1.0,  pop_millions: 231.4, urban_pct: 37, gini: 29.6, health_exp_gdp_pct: 3.4  },
    { country: "South Korea",      iso: "KR", region: "East Asia",        gdp_per_capita: 32237, hdi: 0.925, life_expectancy: 83.5, literacy_rate: 99,   internet_pct: 97,  co2_per_capita: 11.2, pop_millions: 51.7,  urban_pct: 81, gini: 31.4, health_exp_gdp_pct: 8.8  },
    { country: "Ethiopia",         iso: "ET", region: "Sub-Saharan Africa",gdp_per_capita: 936,  hdi: 0.492, life_expectancy: 67.8, literacy_rate: 52,   internet_pct: 24,  co2_per_capita: 0.2,  pop_millions: 126.5, urban_pct: 23, gini: 35.0, health_exp_gdp_pct: 3.4  },
    { country: "Netherlands",      iso: "NL", region: "Europe",           gdp_per_capita: 56589, hdi: 0.941, life_expectancy: 82.3, literacy_rate: 99,   internet_pct: 96,  co2_per_capita: 8.8,  pop_millions: 17.8,  urban_pct: 93, gini: 28.2, health_exp_gdp_pct: 11.1 },
    { country: "Argentina",        iso: "AR", region: "South America",    gdp_per_capita: 10062, hdi: 0.842, life_expectancy: 76.9, literacy_rate: 99,   internet_pct: 88,  co2_per_capita: 4.2,  pop_millions: 45.8,  urban_pct: 93, gini: 42.3, health_exp_gdp_pct: 9.6  },
    { country: "Egypt",            iso: "EG", region: "Middle East",      gdp_per_capita: 3574,  hdi: 0.731, life_expectancy: 72.1, literacy_rate: 73,   internet_pct: 72,  co2_per_capita: 2.5,  pop_millions: 105.0, urban_pct: 43, gini: 31.5, health_exp_gdp_pct: 5.3  },
    { country: "Vietnam",          iso: "VN", region: "Southeast Asia",   gdp_per_capita: 3756,  hdi: 0.703, life_expectancy: 74.9, literacy_rate: 96,   internet_pct: 78,  co2_per_capita: 3.4,  pop_millions: 98.2,  urban_pct: 38, gini: 36.1, health_exp_gdp_pct: 5.9  },
    { country: "Poland",           iso: "PL", region: "Europe",           gdp_per_capita: 18026, hdi: 0.880, life_expectancy: 77.7, literacy_rate: 99,   internet_pct: 91,  co2_per_capita: 8.6,  pop_millions: 38.1,  urban_pct: 60, gini: 30.8, health_exp_gdp_pct: 6.5  },
    { country: "Kenya",            iso: "KE", region: "Sub-Saharan Africa",gdp_per_capita: 2173, hdi: 0.601, life_expectancy: 67.4, literacy_rate: 82,   internet_pct: 40,  co2_per_capita: 0.4,  pop_millions: 55.0,  urban_pct: 29, gini: 40.8, health_exp_gdp_pct: 4.9  },
  ],
};
